// ============================================================================
// GRIMOIRE D'AETHELGARD - SORTS ARCANIQUES
// Magie savante, intellectuelle, manipulation de l'énergie magique brute
// ============================================================================

export interface Spell {
  id: string;
  name: string;
  school: 'arcane' | 'divine' | 'primal' | 'shadow' | 'seal';
  level: number;
  manaCost: number;
  castTime: string;
  range: string;
  duration: string;
  components: string[];
  description: string;
  damage?: string;
  healing?: string;
  effect: string;
  higherLevels?: string;
  classes: string[];
  synergy?: string;
  lore: string;
}

export const ARCANE_SPELLS: Spell[] = [
  // ======================== NIVEAU 1 ========================
  {
    id: 'arc-001',
    name: 'Projectile Arcanique',
    school: 'arcane',
    level: 1,
    manaCost: 2,
    castTime: '1 action',
    range: '36m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le lanceur canalise l\'energie arcanique pure en un ou plusieurs dards lumineux qui frappent unerringly leurs cibles. Les projectiles tracent des trajectoires impossibles, contournant obstacles et allies pour atteindre leur destination avec une precision absolue.',
    damage: '1d4+1 force par projectile (3 projectiles)',
    effect: 'Touche automatiquement. Chaque projectile inflige 1d4+1 degats de force. Les projectiles peuvent cibler une ou plusieurs creatures visibles a portee.',
    higherLevels: 'Un projectile supplementaire par niveau au-dela du 1er.',
    classes: ['Mage', 'Arcaniste', 'Erudit'],
    synergy: 'Combine avec Bouclier de Force pour un style de combat arcanique defensif.',
    lore: 'Premier sort enseigne a l\'Academie de Solaureus, le Projectile Arcanique est considere comme la pierre angulaire de toute formation magique. Les archives de l\'Academie attestent que ce sort fut codifie par l\'Archimage Thelindra au Deuxieme Age.'
  },
  {
    id: 'arc-002',
    name: 'Bouclier de Force',
    school: 'arcane',
    level: 1,
    manaCost: 2,
    castTime: '1 reaction',
    range: 'Personnel',
    duration: '1 round',
    components: ['Verbal', 'Somatique'],
    description: 'Un bouclier de force translucide apparait instantanement devant le lanceur, deviant les attaques entrantes avec une efficacite remarquable. Le bouclier brille d\'une lueur bleue et emet un son cristallin lorsqu\'il absorbe un impact.',
    effect: '+5 a la CA jusqu\'au debut du prochain tour. Annule egalement les degats de Projectile Arcanique si cible par ce sort.',
    classes: ['Mage', 'Arcaniste', 'Chevalier-Mage'],
    synergy: 'Annule completement Projectile Arcanique. Combine avec Mur de Force pour une defense en couches.',
    lore: 'Le Bouclier de Force fut developpe par les Chevaliers-Mages de l\'ancien Empire d\'Aethermoor comme reponse defensive aux assauts magiques. Sa simplicite et son efficacite en font un sort universellement respecte.'
  },
  {
    id: 'arc-003',
    name: 'Detection de Magie',
    school: 'arcane',
    level: 1,
    manaCost: 1,
    castTime: '1 action',
    range: '9m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'Les yeux du lanceur se teintent d\'un eclat dore tandis qu\'il percoit les auras magiques environnantes. Chaque ecole de magie se manifeste sous une couleur distincte : bleu pour l\'arcane, or pour le divin, vert pour le primal, pourpre pour l\'ombre, et blanc incandescent pour la magie des Sceaux.',
    effect: 'Detecte la presence de magie dans un rayon de 9m. Revele l\'ecole de magie et l\'intensite approximative. Peut percevoir la magie a travers la plupart des barrieres, sauf 30cm de pierre, 2cm de metal ou une fine couche de plomb.',
    classes: ['Mage', 'Arcaniste', 'Erudit', 'Barde'],
    synergy: 'Essentiel avant de lancer Contresort. Revele les pieges magiques pour Verrou Arcanique.',
    lore: 'La Detection de Magie est l\'outil fondamental de tout chercheur arcanique. Dans les ruines des civilisations anciennes d\'Aethelgard, ce sort a permis la decouverte de nombreux artefacts lies aux Cinq Sceaux.'
  },
  {
    id: 'arc-004',
    name: 'Lumiere Eternelle',
    school: 'arcane',
    level: 1,
    manaCost: 1,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (une luciole ou du phosphore)'],
    description: 'Le lanceur insuffle une lumiere arcanique permanente dans un objet qu\'il touche. La lueur emise est douce mais constante, et ne projette aucune chaleur. La couleur de la lumiere reflete inconsciemment l\'humeur du lanceur au moment de l\'incantation.',
    effect: 'L\'objet touche emet une lumiere vive dans un rayon de 6m et une lumiere faible sur 6m supplementaires. Le sort persiste indefiniment sauf dissipation. Maximum 3 lumieres actives simultanement par lanceur.',
    classes: ['Mage', 'Arcaniste', 'Erudit', 'Barde', 'Pretre'],
    lore: 'Les salles de l\'Academie de Solaureus sont eclairees par des milliers de Lumieres Eternelles lancees par des generations d\'etudiants. Certaines brillent depuis plus de trois siecles, temoins silencieux de l\'histoire de l\'institution.'
  },

  // ======================== NIVEAU 2 ========================
  {
    id: 'arc-005',
    name: 'Fleches Guidees',
    school: 'arcane',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: '30m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (une plume de faucon)'],
    description: 'Le lanceur conjure des fleches d\'energie pure qui s\'elancent en spirale avant de fondre sur leurs cibles avec une precision chirurgicale. Les fleches ajustent leur trajectoire en temps reel, rendant l\'esquive quasi impossible.',
    damage: '2d6+INT force',
    effect: 'Attaque a distance magique avec avantage. Les fleches ignorent les couverts partiels. Si la premiere touche, la seconde a un bonus de +2 supplementaire.',
    higherLevels: 'Une fleche supplementaire par 2 niveaux au-dela du 2e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Apres Detection de Magie, les fleches peuvent cibler specifiquement les sources magiques detectees.',
    lore: 'Developpe par les tireurs d\'elite arcaniques de la Tour de Verre, ce sort combine precision mathematique et intuition magique. Il est particulierement prise lors des joutes arcaniques de Solaureus.'
  },
  {
    id: 'arc-006',
    name: 'Verrou Arcanique',
    school: 'arcane',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (poudre d\'or d\'une valeur de 25 po)'],
    description: 'Le lanceur trace des runes de verrouillage sur une porte, un coffre ou tout autre mecanisme de fermeture. Les runes s\'enfoncent dans la matiere et deviennent invisibles, laissant une protection magique indelebile.',
    effect: 'Verrouille magiquement un objet fermable. Le DD pour crocheter augmente de 10. Le lanceur peut definir un mot de passe verbal ou une condition de deverrouillage. Peut etre supprime par Dissipation de la Magie.',
    classes: ['Mage', 'Arcaniste', 'Erudit'],
    synergy: 'Peut etre renforce par Mur de Force pour creer une salle forte arcanique.',
    lore: 'Les marchands d\'Havrebrume paient grassement pour que leurs entrepots soient proteges par des Verrous Arcaniques. On raconte que le tresor royal de Coeurfer est scelle par sept verrous superposes, chacun lance par un archimage different.'
  },
  {
    id: 'arc-007',
    name: 'Invisibilite',
    school: 'arcane',
    level: 2,
    manaCost: 5,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un cil enrobe de gomme arabique)'],
    description: 'La creature touchee devient completement invisible, y compris tout ce qu\'elle porte et transporte. La lumiere courbe autour du sujet, le rendant indectable a l\'oeil nu. Cependant, le sort ne masque ni les sons ni les odeurs.',
    effect: 'La cible devient invisible. Les attaques contre elle ont un desavantage. Le sort prend fin si la cible attaque ou lance un sort. Avantage aux jets de Discretion.',
    higherLevels: 'Au niveau 4+, une cible supplementaire par 2 niveaux au-dela.',
    classes: ['Mage', 'Arcaniste', 'Barde'],
    synergy: 'Combine avec Levitation pour une infiltration aerienne invisible.',
    lore: 'L\'Invisibilite est l\'un des sorts les plus convoites et les plus regulementes d\'Aethelgard. Son usage est strictement controle a Solaureus, ou des cristaux de revelation sont installes aux entrees des quartiers sensibles.'
  },
  {
    id: 'arc-008',
    name: 'Levitation',
    school: 'arcane',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (une boucle de fil de cuivre)'],
    description: 'Le lanceur defie la gravite, soulevant une creature ou un objet dans les airs. Le sujet flotte doucement, pouvant monter ou descendre a volonte du lanceur, mais incapable de se deplacer horizontalement sans aide.',
    effect: 'La cible s\'eleve verticalement jusqu\'a 6m par round, maximum 30m. Peut rester suspendue en l\'air. Une creature non consentante peut resister (JdS CON). Poids maximum: 250 kg.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Invisibilite pour une infiltration aerienne. Utile pour positionner avant Boule de Feu.',
    lore: 'Les architectes arcaniques de l\'ancien Aethermoor utilisaient la Levitation pour construire les tours impossibles dont les ruines parsement encore le paysage d\'Aethelgard. La Tour Celeste de Solaureus fut entierement batie grace a ce sort.'
  },

  // ======================== NIVEAU 3 ========================
  {
    id: 'arc-009',
    name: 'Boule de Feu',
    school: 'arcane',
    level: 3,
    manaCost: 8,
    castTime: '1 action',
    range: '45m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (une bille de soufre et de salpetre)'],
    description: 'Une perle de lumiere incandescente jaillit du doigt du lanceur et file vers le point designe avant d\'exploser en une deflagration devoratrice. Les flammes s\'enroulent autour des obstacles, ne laissant aucun recoin epargne dans la zone d\'effet.',
    damage: '8d6 feu',
    effect: 'Explosion dans une sphere de 6m de rayon. Chaque creature dans la zone effectue un JdS DEX. Degats divises par deux en cas de reussite. Enflamme les objets inflammables non portes.',
    higherLevels: '+1d6 degats par niveau au-dela du 3e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Devastateur apres Levitation (attaque plongeante). Combine avec Tempete de Glace pour un choc thermique (+2d6 degats).',
    lore: 'La Boule de Feu est le sort de combat arcanique par excellence. Lors de la Bataille des Cinq Flammes, l\'Archimage Veridian aurait lance sept Boules de Feu consecutives, creant le cratere aujourd\'hui connu sous le nom du Lac des Cendres.'
  },
  {
    id: 'arc-010',
    name: 'Contresort',
    school: 'arcane',
    level: 3,
    manaCost: 6,
    castTime: '1 reaction',
    range: '18m',
    duration: 'Instantane',
    components: ['Somatique'],
    description: 'D\'un geste vif, le lanceur projette une vague d\'energie disruptive qui interfere avec le tissage magique d\'un autre lanceur. Les fils de mana se delitent et le sort adverse avorte dans une gerbe d\'etincelles.',
    effect: 'Interrompt un sort de niveau 3 ou inferieur en cours d\'incantation. Pour les sorts de niveau superieur, jet d\'INT DD 10 + niveau du sort. En cas d\'echec, le Contresort est gaspille.',
    higherLevels: 'Interrompt automatiquement les sorts de niveau egal ou inferieur au niveau auquel Contresort est lance.',
    classes: ['Mage', 'Arcaniste', 'Erudit'],
    synergy: 'Detection de Magie active donne +2 au jet de Contresort contre les sorts de haut niveau.',
    lore: 'Le Contresort est une discipline veneree a l\'Academie de Solaureus, ou les duels arcaniques se gagnent souvent par la maitrise de cette riposte. Les meilleurs contresorteurs sont appeles les Tisserands-Briseurs.'
  },
  {
    id: 'arc-011',
    name: 'Vol',
    school: 'arcane',
    level: 3,
    manaCost: 7,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (une plume d\'aigle)'],
    description: 'Des ailes d\'energie translucide se deploient dans le dos de la creature touchee, lui conferant une liberte de mouvement totale dans les trois dimensions. Le vol est intuitif et gracieux, comme si le sujet avait toujours connu le ciel.',
    effect: 'La cible obtient une vitesse de vol de 18m. Si le sort se termine en vol, la cible tombe sauf si elle peut empecher la chute.',
    higherLevels: 'Au niveau 5+, la duree passe a 1 heure. Au niveau 7+, une cible supplementaire.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Boule de Feu pour des frappes aeriennes devastatrices.',
    lore: 'Le Vol est l\'aspiration fondamentale de tout arcaniste. Les Chevaucheurs de Vent de l\'Ere des Sceaux auraient combat dans les cieux au-dessus d\'Aethelgard, leurs batailles tracant des sillons lumineux dans la nuit.'
  },
  {
    id: 'arc-012',
    name: 'Clairvoyance',
    school: 'arcane',
    level: 3,
    manaCost: 7,
    castTime: '10 minutes',
    range: '1,5 km',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un oeil de verre d\'une valeur de 100 po)'],
    description: 'Le lanceur projette un capteur sensoriel invisible a un endroit qu\'il connait ou qu\'il peut decrire. A travers ce capteur, il peut voir ou entendre comme s\'il y etait, percevant le monde depuis un point fixe dans l\'espace.',
    effect: 'Cree un capteur invisible a un emplacement connu. Le lanceur peut voir OU entendre a travers le capteur (choix a chaque tour). Le capteur est detectable par Detection de Magie.',
    classes: ['Mage', 'Arcaniste', 'Erudit'],
    synergy: 'Permet de reperer une zone avant Teleportation pour un voyage sur.',
    lore: 'Les espions arcaniques de la Guilde des Ombres utilisent frequemment la Clairvoyance pour surveiller les mouvements des factions rivales. Le Conseil de Solaureus dispose de salles de clairvoyance permettant de surveiller les frontieres du royaume.'
  },

  // ======================== NIVEAU 4 ========================
  {
    id: 'arc-013',
    name: 'Mur de Force',
    school: 'arcane',
    level: 4,
    manaCost: 12,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un eclat de cristal transparent)'],
    description: 'Un pan de force invisible et indestructible se materialise a l\'endroit designe. Le mur est parfaitement transparent et impenetrable, bloquant aussi bien les attaques physiques que magiques. Meme le souffle d\'un dragon ne peut l\'entamer.',
    effect: 'Cree un mur invisible de 3m x 3m x 3mm. Immune a tous les degats sauf Desintegration. Rien ne peut le traverser physiquement. Peut etre oriente horizontalement ou verticalement. Maximum 10 panneaux connectes.',
    classes: ['Mage', 'Arcaniste', 'Chevalier-Mage'],
    synergy: 'Combine avec Verrou Arcanique pour une defense impenetrable. Piege les ennemis pour Boule de Feu.',
    lore: 'Le Mur de Force est considere comme le chef-d\'oeuvre de la magie defensive. Lors du Siege de Coeurfer, un unique mage a tenu la breche des murailles pendant trois jours grace a des Murs de Force successifs.'
  },
  {
    id: 'arc-014',
    name: 'Porte Dimensionnelle',
    school: 'arcane',
    level: 4,
    manaCost: 10,
    castTime: '1 action',
    range: '150m',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'L\'espace se plie brievement tandis que le lanceur ouvre une dechirure dans le tissu de la realite. En un clignement d\'oeil, il se retrouve a un autre endroit, la distance parcourue n\'etant qu\'un pas a travers une dimension intermediaire.',
    effect: 'Teleportation instantanee jusqu\'a 150m vers un lieu visible ou decrit. Peut emmener une creature consentante de taille M ou moins. Arrive a l\'endroit exact desire ou au point le plus proche disponible.',
    classes: ['Mage', 'Arcaniste', 'Barde'],
    synergy: 'Sortie d\'urgence apres avoir lance Boule de Feu au corps a corps.',
    lore: 'Les messagers arcaniques de la Couronne utilisent des Portes Dimensionnelles enchainees pour traverser le royaume en quelques heures. On murmure que certains passages dimensionnels laissent des cicatrices dans la realite qu\'exploitent les adeptes de la magie de l\'Ombre.'
  },
  {
    id: 'arc-015',
    name: 'Metamorphose',
    school: 'arcane',
    level: 4,
    manaCost: 12,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un cocon de chenille)'],
    description: 'Le corps de la cible se transforme en celui d\'une autre creature, ses os craquent et se reforment, sa peau ondule et se remodele. La transformation est complete mais temporaire, l\'essence originelle de la creature subsistant sous la nouvelle forme.',
    effect: 'Transforme une creature en une bete de FP egal ou inferieur a son niveau. La cible adopte les stats de la bete mais conserve sa personnalite et ses souvenirs. Si les PV de la bete tombent a 0, la cible reprend sa forme.',
    higherLevels: 'Au niveau 6+, peut transformer en creature de tout type (pas seulement bete).',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Vol pour transformer un allie en creature volante puissante.',
    lore: 'La Metamorphose est un art delicat qui exige une connaissance parfaite de l\'anatomie. Les polymorphistes de l\'Ere des Sceaux auraient pu maintenir des formes alternatives pendant des annees, une maitrise aujourd\'hui perdue.'
  },
  {
    id: 'arc-016',
    name: 'Tempete de Glace',
    school: 'arcane',
    level: 4,
    manaCost: 11,
    castTime: '1 action',
    range: '90m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (une pincee de poussiere et quelques gouttes d\'eau)'],
    description: 'Un deluge de grelons durs comme la pierre s\'abat sur une zone circulaire, suivis d\'une vague de froid mordant qui gele tout sur son passage. Le sol se couvre d\'une couche de glace traitresse, transformant le champ de bataille.',
    damage: '2d8 contondant + 4d6 froid',
    effect: 'Zone de 6m de rayon, JdS DEX pour demi-degats. La zone devient un terrain difficile recouvert de glace pendant 1 minute. Les creatures qui commencent leur tour dans la zone doivent reussir un JdS DEX ou tomber a terre.',
    higherLevels: '+1d8 contondant par niveau au-dela du 4e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Apres Boule de Feu, le choc thermique inflige +2d6 degats supplementaires.',
    lore: 'La Tempete de Glace est l\'heritage des mages du Grand Nord d\'Aethelgard, ou les hivers sont si rudes que la magie elle-meme gele. Les Forgegivre de Coeurfer ont perfectionne ce sort pour defendre les cols de montagne.'
  },

  // ======================== NIVEAU 5 ========================
  {
    id: 'arc-017',
    name: 'Teleportation',
    school: 'arcane',
    level: 5,
    manaCost: 16,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le lanceur et ses compagnons sont enveloppes dans un cocon d\'energie avant de se dissoudre dans le flux arcanique. Un instant plus tard, ils se reforment a leur destination, parfois avec de legeres imprecisions dues aux perturbations du tissu magique.',
    effect: 'Teleporte le lanceur et jusqu\'a 8 creatures consentantes vers une destination connue. La precision depend de la familiarite : tres familier (sans erreur), vu occasionnellement (1d10 : 1-3 erreur de 1d10 km), decrit (1d10 : 1-5 erreur, 6-10 zone similaire).',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Clairvoyance prealable garantit une teleportation sans erreur.',
    lore: 'Les Cercles de Teleportation permanents d\'Aethelgard sont les arteres vitales du commerce et de la communication. Leur destruction par les forces de l\'Ombre lors de la Guerre des Sceaux a plonge le continent dans l\'isolement.'
  },
  {
    id: 'arc-018',
    name: 'Animation d\'Objet',
    school: 'arcane',
    level: 5,
    manaCost: 14,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Les objets inanimes s\'eveillent a la volonte du lanceur, se soulevant et se mouvant comme dotes d\'une vie propre. Des epees dansent dans les airs, des chaises chargent les ennemis, et des armures vides marchent au combat.',
    effect: 'Anime jusqu\'a 10 objets non magiques de taille P, 5 de taille M, 2 de taille G ou 1 de taille TG. Chaque objet a des stats basees sur sa taille et agit selon les ordres du lanceur (action bonus pour commander).',
    higherLevels: '+2 objets de taille P par niveau au-dela du 5e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Metamorphose pour creer une armee de diversion.',
    lore: 'Les golems d\'entrainement de l\'Academie de Solaureus sont des objets animes de facon permanente, une prouesse qui depasse de loin ce sort temporaire. L\'Animation d\'Objet rappelle l\'art perdu des Constructeurs du Deuxieme Age.'
  },
  {
    id: 'arc-019',
    name: 'Domination',
    school: 'arcane',
    level: 5,
    manaCost: 16,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Le lanceur projette sa volonte dans l\'esprit d\'une creature, ecrasant ses pensees et prenant le controle de son corps. La cible reste consciente mais impuissante, piegee dans son propre esprit tandis que le lanceur dirige ses actions.',
    effect: 'La cible effectue un JdS SAG. En cas d\'echec, le lanceur controle totalement ses actions. La cible repete le JdS a chaque fois qu\'elle subit des degats. Les creatures avec INT 4+ ont un bonus au JdS.',
    higherLevels: 'Au niveau 7+, duree de 10 minutes. Au niveau 9+, duree de 1 heure.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Clairvoyance pour dominer a distance.',
    lore: 'La Domination est un sort controverse, interdit dans plusieurs nations d\'Aethelgard. Son usage non autorise est passible de bannissement magique. Les Tisseurs d\'Ombre l\'utilisent sans scrupule, une raison supplementaire pour les craindre.'
  },
  {
    id: 'arc-020',
    name: 'Desintegration',
    school: 'arcane',
    level: 5,
    manaCost: 18,
    castTime: '1 action',
    range: '18m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un aimant et une pincee de poussiere)'],
    description: 'Un mince rayon de lumiere verte jaillit du doigt du lanceur, reduisant en fine poussiere grise tout ce qu\'il touche. Le rayon desagrege la matiere au niveau moleculaire, ne laissant rien d\'autre qu\'un tas de cendres.',
    damage: '10d6+40 force',
    effect: 'Attaque a distance magique. Si la cible tombe a 0 PV, elle est completement desintegree en poussiere. Detruit automatiquement un Mur de Force ou toute creation de force. Les objets non magiques de taille G ou moins sont detruits.',
    higherLevels: '+3d6 degats par niveau au-dela du 5e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Seul sort capable de detruire un Mur de Force.',
    lore: 'La Desintegration est l\'arme ultime de l\'arcaniste de combat. L\'Archimage Noctus, avant sa chute dans l\'Ombre, aurait desintegre une montagne entiere pour reveler le Sceau de la Terre cache en son coeur.'
  },

  // ======================== NIVEAU 6 ========================
  {
    id: 'arc-021',
    name: 'Globe d\'Invulnerabilite',
    school: 'arcane',
    level: 6,
    manaCost: 22,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (une perle de verre ou de cristal)'],
    description: 'Une sphere de force chatoyante englobe le lanceur, creant une zone ou la magie inferieure ne peut penetrer. Les sorts de faible niveau se brisent contre la surface du globe comme des vagues contre un rocher.',
    effect: 'Cree une sphere immobile de 3m de rayon centree sur le lanceur. Les sorts de niveau 5 ou inferieur ne peuvent affecter les creatures ou objets a l\'interieur du globe, meme s\'ils sont lances avec un emplacement superieur.',
    higherLevels: 'Au niveau 7+, bloque les sorts de niveau 6 ou inferieur, etc.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Protection parfaite pendant que les allies lancent des sorts offensifs depuis l\'interieur.',
    lore: 'Le Globe d\'Invulnerabilite est le symbole de la maitrise arcanique supreme. Seuls les Archimages de l\'Academie ont traditionnellement le droit de l\'enseigner, un privilege qu\'ils gardent jalousement.'
  },
  {
    id: 'arc-022',
    name: 'Contingence',
    school: 'arcane',
    level: 6,
    manaCost: 20,
    castTime: '10 minutes',
    range: 'Personnel',
    duration: '10 jours',
    components: ['Verbal', 'Somatique', 'Materiel (une statuette de soi-meme en ivoire incrustee de gemmes, valeur 1500 po)'],
    description: 'Le lanceur tisse un sort dans un etat de latence, lie a un declencheur specifique. Quand la condition est remplie, le sort contingent se libere instantanement, souvent au moment le plus critique.',
    effect: 'Stocke un sort de niveau 5 ou inferieur qui se declenche automatiquement quand une condition specifiee est remplie. Un seul sort contingent actif a la fois. Exemples : Bouclier de Force si attaque, Teleportation si PV < 10.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Piege absolu : Contingence + Desintegration declenchee par une intrusion.',
    lore: 'Les Archimages les plus paranoiaques d\'Aethelgard maintiennent en permanence plusieurs couches de Contingence. On dit que l\'Archimage Thelindra avait tellement de contingences actives que sa mort declencha une cascade de sorts qui detruisit sa tour.'
  },
  {
    id: 'arc-023',
    name: 'Creation de Demi-plan',
    school: 'arcane',
    level: 6,
    manaCost: 24,
    castTime: '1 action',
    range: '18m',
    duration: '1 heure',
    components: ['Somatique'],
    description: 'Une porte luminescente apparait dans le vide, s\'ouvrant sur un espace dimensionnel cree par la volonte du lanceur. Au-dela se trouve une piece de 9m de cote, vide et silencieuse, existant dans un espace entre les mondes.',
    effect: 'Cree un espace extradimensionnel accessible par une porte visible. La piece fait 9m x 9m x 9m. L\'atmosphere est respirable. A la fin du sort, tout ce qui s\'y trouve est expulse dans l\'espace le plus proche. Chaque lancement subsequent sur le meme plan l\'agrandit.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Contingence pour un refuge d\'urgence. Peut servir de prison dimensionnelle.',
    lore: 'Les plus grands arcanistes d\'Aethelgard maintiennent des demi-plans personnels comme laboratoires et bibliotheques. Le legendaire Demi-plan d\'Aldric contiendrait l\'integralite des connaissances du Deuxieme Age, si seulement quelqu\'un pouvait le retrouver.'
  },
  {
    id: 'arc-024',
    name: 'Chaine d\'Eclairs',
    school: 'arcane',
    level: 6,
    manaCost: 22,
    castTime: '1 action',
    range: '45m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un morceau d\'ambre, une tige de verre et trois epingles en argent)'],
    description: 'Un arc electrique devastateur jaillit vers la cible principale avant de bondir vers les creatures adjacentes dans un ballet mortel de foudre. L\'eclair saute de cible en cible, perdant peu de puissance a chaque bond.',
    damage: '10d8 foudre (cible principale), 5d8 foudre (cibles secondaires)',
    effect: 'L\'eclair frappe une cible principale puis rebondit sur 3 cibles secondaires dans un rayon de 9m. JdS DEX pour demi-degats. Les cibles secondaires subissent la moitie des degats de la cible principale.',
    higherLevels: '+1 cible secondaire par niveau au-dela du 6e.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Apres Tempete de Glace, les cibles mouillees ont un desavantage au JdS.',
    lore: 'La Chaine d\'Eclairs est le sort de predilection des Tempetiers, un ordre de mages de guerre qui canalisent la puissance des orages. Lors de la defense de Havrebrume, une Chaine d\'Eclairs aurait foudroye une flotte entiere de pirates.'
  },

  // ======================== NIVEAU 7 ========================
  {
    id: 'arc-025',
    name: 'Inversion Temporelle',
    school: 'arcane',
    level: 7,
    manaCost: 30,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un sablier en platine d\'une valeur de 5000 po)'],
    description: 'Le lanceur fait reculer le temps de quelques secondes pour lui-meme, revenant a l\'etat ou il se trouvait un instant auparavant. Ses blessures se referment, son mana se restaure partiellement, et il se retrouve a sa position precedente.',
    effect: 'Le lanceur revient a l\'etat qu\'il avait au debut de son tour precedent : PV, position, etats. Les effets sur le monde exterieur ne sont pas annules. Utilisable une seule fois par jour.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Permet de relancer un Contresort rate ou de retenter une Teleportation imprecise.',
    lore: 'L\'Inversion Temporelle touche aux forces les plus fondamentales d\'Aethelgard. Les chronomaniciens sont rares et respectes, car manipuler le temps attire l\'attention des entites qui veillent sur le flux temporel.'
  },
  {
    id: 'arc-026',
    name: 'Emprisonnement',
    school: 'arcane',
    level: 7,
    manaCost: 28,
    castTime: '1 minute',
    range: '9m',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (composante speciale selon la forme, valeur minimum 500 po)'],
    description: 'Le lanceur enferme une creature dans une prison magique dont la forme varie selon la composante utilisee : enchainee, enterree, endormie, rapetissee dans une gemme ou enfermee dans un demi-plan minuscule.',
    effect: 'La cible effectue un JdS SAG. En cas d\'echec, elle est emprisonnee selon la forme choisie. La prison est permanente jusqu\'a dissipation ou accomplissement d\'une condition de liberation definie par le lanceur.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Contingence declenchant Emprisonnement si un ennemi specifique approche.',
    lore: 'On raconte que les Scelles Primordiaux utilisaient une forme superieure d\'Emprisonnement pour maintenir les entites du Vide hors de la realite. Certains pretendent que les Cinq Sceaux eux-memes ne sont que des Emprisonnements a l\'echelle cosmique.'
  },
  {
    id: 'arc-027',
    name: 'Mot de Pouvoir: Etourdissement',
    school: 'arcane',
    level: 7,
    manaCost: 26,
    castTime: '1 action',
    range: '18m',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le lanceur prononce un mot de puissance brute qui frappe l\'esprit de la cible comme un coup de tonnerre. Ce mot n\'appartient a aucune langue connue — c\'est un fragment du langage primordial de la creation, dangereux a prononcer comme a entendre.',
    effect: 'Si la cible a 150 PV ou moins, elle est etourdie (aucun JdS). A la fin de chaque tour, JdS CON DD 17 pour mettre fin a l\'etourdissement. Si la cible a plus de 150 PV, aucun effet.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Suivi de Desintegration sur la cible etourdie (avantage a l\'attaque).',
    lore: 'Les Mots de Pouvoir sont des vestiges du Verbe Primordial qui aurait faconne Aethelgard. Chaque utilisation erode legerement la voix du lanceur, et les arcanistes qui en abusent finissent par perdre la parole.'
  },
  {
    id: 'arc-028',
    name: 'Simulacre',
    school: 'arcane',
    level: 7,
    manaCost: 32,
    castTime: 'rituel 12h',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (neige, cheveux de la creature, poudre de rubis d\'une valeur de 1500 po)'],
    description: 'Le lanceur faconne une replique illusoire mais partiellement reelle d\'une creature. Le simulacre est identique en apparence et possede la moitie des PV et capacites de l\'original, mais il est incapable d\'apprendre ou de regagner des sorts.',
    effect: 'Cree un double de la creature avec 50% de ses PV max, ses sorts (non recuperables) et ses capacites. Le simulacre obeit au lanceur. Ne peut pas regagner de PV sauf par reparation. Un seul simulacre actif a la fois.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Le simulacre peut maintenir la Concentration sur un sort pendant que le lanceur en utilise un autre.',
    lore: 'Le Simulacre est un art interdit par l\'Academie de Solaureus depuis que l\'Archimage Morwen crea un simulacre de lui-meme qui tenta de le remplacer. L\'incident, connu comme la Duplicite de Morwen, est un avertissement enseigne a tous les apprentis.'
  },

  // ======================== NIVEAU 8 ========================
  {
    id: 'arc-029',
    name: 'Labyrinthe Dimensionnel',
    school: 'arcane',
    level: 8,
    manaCost: 36,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'La cible est aspiree dans un labyrinthe extradimensionnel aux couloirs infinis et aux murs changeants. L\'espace se replie sur lui-meme, les passages menent en cercle, et le temps semble s\'ecouler differemment entre les murs de ce dedale impossible.',
    effect: 'La cible est bannie dans un labyrinthe dimensionnel (aucun JdS). A chaque tour, elle peut tenter un jet d\'INT DD 20 pour s\'echapper. Les creatures avec une intelligence de 2 ou moins ne peuvent pas tenter de s\'echapper.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Retire un ennemi du combat pendant que le groupe gere les autres menaces.',
    lore: 'Le Labyrinthe Dimensionnel est inspire des legendes du Dedale de Miroir, une prison extradimensionnelle qui existerait quelque part entre les plans. On dit que certains prisonniers y errent encore apres des siecles.'
  },
  {
    id: 'arc-030',
    name: 'Clone',
    school: 'arcane',
    level: 8,
    manaCost: 40,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 1000 po, un recipient scelle, et un morceau de chair de la creature)'],
    description: 'Le lanceur cultive une replique inerte de lui-meme ou d\'une autre creature dans un recipient scelle. Ce corps croit lentement, et si l\'original meurt, son ame migre instantanement vers le clone, lui conferant une forme de vie eternelle.',
    effect: 'Cree un corps inerte qui sert de receptacle pour l\'ame. Si la creature originale meurt, son ame se transfere dans le clone (si libre et consentante). Le clone peut etre d\'un age different. Delai de maturation : 120 jours.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Combine avec Contingence (Teleportation vers le clone) pour un systeme de survie ultime.',
    lore: 'Le Clone est le secret de la longevite des Archimages d\'Aethelgard. L\'Archimage Thelindra serait sur son septieme corps, chacun cultive avec soin dans les profondeurs de l\'Academie. Nul ne sait combien d\'autres arcanistes partagent ce secret.'
  },
  {
    id: 'arc-031',
    name: 'Controle du Temps',
    school: 'arcane',
    level: 8,
    manaCost: 38,
    castTime: '1 action',
    range: '30m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (un sablier en mithral)'],
    description: 'Le lanceur manipule le flux temporel dans une zone, accelerant ou ralentissant le temps selon sa volonte. Les creatures affectees semblent se mouvoir dans de la melasse ou au contraire vibrer d\'une vitesse surnaturelle.',
    effect: 'Choisir acceleration ou deceleration dans une sphere de 12m. Acceleration : les allies agissent deux fois par round. Deceleration : les ennemis n\'agissent qu\'un round sur deux. JdS SAG pour les cibles non consentantes.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Acceleration + Chaine d\'Eclairs = double salve de foudre devastatrice.',
    lore: 'Le Controle du Temps est le domaine exclusif des Chronomaniciens, un ordre secret au sein de l\'Academie. Ils pretendent que le temps n\'est pas lineaire mais spiral, et que le manipuler ne fait que reveler ses boucles naturelles.'
  },
  {
    id: 'arc-032',
    name: 'Tempete Arcanique',
    school: 'arcane',
    level: 8,
    manaCost: 35,
    castTime: '1 action',
    range: '300m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le lanceur libere une tempete d\'energie arcanique brute qui balaie une vaste zone. Des eclairs multicolores zebrent le ciel, des vagues de force soulevent la terre, et la magie elle-meme semble hurler de douleur tandis que le tissu de la realite est mis a rude epreuve.',
    damage: '6d10 force + 4d10 foudre',
    effect: 'Zone de 12m de rayon. JdS DEX pour demi-degats. Dissipe automatiquement tous les sorts de niveau 5 ou inferieur dans la zone. 25% de chance d\'ouvrir une breche temporaire vers un autre plan.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Dissipe les defenses ennemies tout en infligeant des degats massifs.',
    lore: 'La Tempete Arcanique est l\'equivalent magique d\'une arme de destruction massive. Son utilisation lors de la Guerre des Sceaux aurait provoque les Cicatrices Arcaniques, des zones ou la magie est corrompue de facon permanente.'
  },

  // ======================== NIVEAU 9 ========================
  {
    id: 'arc-033',
    name: 'Souhait Limite',
    school: 'arcane',
    level: 9,
    manaCost: 45,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le lanceur puise dans les forces fondamentales de la realite pour formuler un souhait. La magie arcanique se plie a sa volonte, accomplissant des prouesses qui defient les lois naturelles. Cependant, le cout est immense et le resultat pas toujours exactement celui escompte.',
    effect: 'Reproduit tout sort de niveau 8 ou inferieur sans composantes. Ou : annuler un evenement recent, restaurer un objet, accorder une resistance, etc. Le MJ determine les limitations. Apres utilisation, 33% de chance de ne plus jamais pouvoir lancer ce sort.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Sort universel — peut reproduire tout sort de niveau inferieur.',
    lore: 'Le Souhait Limite est l\'un des plus grands accomplissements de la magie mortelle. Seuls les Archimages les plus puissants osent le lancer, car chaque souhait consume une part de l\'ame du lanceur. On dit que la realite elle-meme resiste a etre ainsi forcee.'
  },
  {
    id: 'arc-034',
    name: 'Arret du Temps',
    school: 'arcane',
    level: 9,
    manaCost: 44,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le monde entier se fige dans un silence absolu tandis que le lanceur seul continue d\'exister dans le flux temporel. Les gouttes de pluie pendent en l\'air, les flammes sont immobiles, et meme la lumiere semble s\'arreter.',
    effect: 'Le lanceur obtient 1d4+1 tours supplementaires pendant lesquels le temps est arrete pour toutes les autres creatures. Ne peut affecter ou endommager les creatures figees. Les sorts a zone d\'effet se declenchent quand le temps reprend.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Permet de placer plusieurs Boules de Feu qui explosent simultanement quand le temps reprend.',
    lore: 'L\'Arret du Temps est la technique ultime des Chronomaniciens. La legende raconte que le Chronomanicien Aelar a un jour arrete le temps pendant un an entier, vivant seul dans un monde fige. Quand il a relache le sort, il etait devenu fou.'
  },
  {
    id: 'arc-035',
    name: 'Desintegration Supreme',
    school: 'arcane',
    level: 9,
    manaCost: 42,
    castTime: '1 action',
    range: '30m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant noir d\'une valeur de 5000 po qui est consomme)'],
    description: 'Une version titanesque du rayon de desintegration, un faisceau de lumiere blanche aveuglante qui consume tout sur son passage. Le rayon est si puissant qu\'il desagrege non seulement la matiere mais aussi les enchantements, les protections et les liens magiques.',
    damage: '20d6+80 force',
    effect: 'Rayon de 1,5m de large sur 30m de long. JdS DEX pour demi-degats. Desintegre toute creature reduite a 0 PV. Traverse et detruit les Murs de Force, Globes d\'Invulnerabilite et autres barrieres magiques. Ignore la resistance a la force.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Apres Arret du Temps, positionner le rayon pour un tir imparable.',
    lore: 'La Desintegration Supreme est un sort de legende, mentionne dans les chroniques mais rarement vu. L\'Archimage Noctus l\'aurait utilise pour ouvrir une breche dans le Sceau de la Terre, un acte qui precipita la Guerre des Sceaux.'
  },
  {
    id: 'arc-036',
    name: 'Portail Permanent',
    school: 'arcane',
    level: 9,
    manaCost: 46,
    castTime: '1 action',
    range: '18m',
    duration: '1 minute (ou permanent avec composante)',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 5000 po, permanent si 25000 po)'],
    description: 'Un portail circulaire de 3m de diametre s\'ouvre dans l\'air, revelant un autre lieu — peut-etre a l\'autre bout du monde, peut-etre dans un autre plan d\'existence. Le bord du portail creptie d\'energie arcanique et l\'air entre les deux espaces se melange.',
    effect: 'Ouvre un portail bidirectionnel vers un lieu connu ou un autre plan. Toute creature peut le traverser. Duree 1 minute ou permanent si la composante couteuse est utilisee. Le portail peut etre ferme par le lanceur a volonte.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Avec Clairvoyance, garantit un portail precis. Peut mener a un Demi-plan existant.',
    lore: 'Les Portails Permanents d\'Aethelgard sont des vestiges du Deuxieme Age, quand les voyages interplanaires etaient monnaie courante. La plupart ont ete detruits ou scelles lors de la Guerre des Sceaux. En creer un nouveau est un exploit digne des Archimages d\'antan.'
  },

  // ======================== NIVEAU 10 ========================
  {
    id: 'arc-037',
    name: 'Apocalypse Arcanique',
    school: 'arcane',
    level: 10,
    manaCost: 60,
    castTime: '1 action',
    range: '1,5 km',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un fragment de meteorite et une larme d\'archimage)'],
    description: 'Le lanceur dechaine la puissance brute de l\'arcane dans sa forme la plus devastatrice. Le ciel se dechire, la terre tremble, et une colonne d\'energie pure descend des cieux, annihilant tout dans la zone d\'impact. C\'est la magie dans son expression la plus terrible et la plus absolue.',
    damage: '20d12 force + 10d12 feu',
    effect: 'Zone de 30m de rayon. JdS DEX DD 22 pour demi-degats. Detruit automatiquement les structures non magiques. Dissipe tous les sorts actifs dans la zone. Cree une zone de magie morte pendant 24h. Le lanceur subit 4d10 degats de retour.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Ne peut etre contree que par Reecriture de la Realite ou un sort de Sceau.',
    lore: 'L\'Apocalypse Arcanique n\'a ete lancee que trois fois dans l\'histoire d\'Aethelgard. Chaque fois, elle a laisse une cicatrice permanente sur le monde. Les Deserts de Cendre, la Mer de Verre et le Cratere d\'Aldric temoignent de sa puissance devastatrice.'
  },
  {
    id: 'arc-038',
    name: 'Reecriture de la Realite',
    school: 'arcane',
    level: 10,
    manaCost: 65,
    castTime: '1 minute',
    range: '90m',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (l\'encre du Codex Primordial, irreplacable)'],
    description: 'Le lanceur modifie les lois fondamentales de la realite dans une zone definie. La gravite, le temps, les elements, les regles memes de la magie — tout peut etre reecrit selon la volonte du lanceur. C\'est l\'acte createur ultime, reservee aux etres qui touchent a la divinite.',
    effect: 'Modifie une loi physique ou magique dans une zone de 30m de rayon : gravite inversee, temps accelere x10, immunite totale a un type de degats, etc. L\'effet est permanent mais le lanceur perd definitivement 2 niveaux de sort maximum.',
    classes: ['Mage'],
    synergy: 'Contre Apocalypse Arcanique en reecrivant la zone pour la rendre immune.',
    lore: 'La Reecriture de la Realite est le domaine des dieux et des Scelles Primordiaux. Qu\'un mortel puisse y acceder est un prodige — ou une abomination. Les rares zones reecrites d\'Aethelgard sont des lieux de pelerinage pour les arcanistes et de terreur pour tous les autres.'
  },
  {
    id: 'arc-039',
    name: 'Ascension',
    school: 'arcane',
    level: 10,
    manaCost: 70,
    castTime: 'rituel 1h',
    range: 'Personnel',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un phylactere en orichalque contenant l\'essence d\'un plan, valeur 50000 po)'],
    description: 'Le lanceur transcende brievement les limites de la condition mortelle, devenant pour un instant un etre de pure energie arcanique. Son corps se dissout en lumiere, ses pensees embrassent la totalite du flux magique, et il percoit la realite telle qu\'elle est veritablement.',
    effect: 'Pendant 10 minutes : immunite a tous les degats, peut lancer des sorts sans composantes ni mana, CA infinie, peut se teleporter librement. A la fin, le lanceur subit 5 niveaux d\'epuisement et ne peut plus lancer de sorts pendant 7 jours.',
    classes: ['Mage'],
    synergy: 'Combinable avec tout sort — c\'est la forme ultime du lanceur.',
    lore: 'L\'Ascension est le reve ultime de tout arcaniste — toucher brievement a la divinite. L\'Archimage Thelindra l\'a accomplie une seule fois, et les dix minutes qu\'elle a passees sous cette forme ont suffi a mettre fin a la Guerre des Sceaux. Elle ne l\'a jamais relancee.'
  },
  {
    id: 'arc-040',
    name: 'Nova Primordiale',
    school: 'arcane',
    level: 10,
    manaCost: 55,
    castTime: '1 action',
    range: '150m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un fragment de Sceau, consomme)'],
    description: 'Le lanceur condense toute l\'energie arcanique environnante en un point infinitesimal avant de la relacher dans une explosion comparable a la naissance d\'une etoile. L\'eclat est visible a des centaines de kilometres et la detonation fait trembler le tissu meme de la realite.',
    damage: '30d10 force + 15d10 radiant',
    effect: 'Sphere de 18m de rayon. JdS CON DD 23 pour demi-degats. Les creatures reduites a 0 PV sont desintegrees. Tous les objets magiques dans la zone doivent reussir un JdS ou perdre leur magie. Zone de magie instable pendant 1 mois.',
    classes: ['Mage', 'Arcaniste'],
    synergy: 'Necessite un fragment de Sceau — synergise avec les sorts de Sceau pour amplifier l\'effet.',
    lore: 'La Nova Primordiale canalise l\'energie des Sceaux eux-memes, ce qui la rend aussi sacrilege que puissante. Son utilisation non autorisee est passible de mort dans toutes les nations d\'Aethelgard, car elle risque d\'affaiblir les Sceaux qui maintiennent le monde.'
  }
];
