// ============================================================================
// GRIMOIRE D'AETHELGARD - SORTS PRIMAUX
// Magie de la nature, des elements, des betes et du pouvoir druidique
// ============================================================================

import { Spell } from './spells-arcane';

export const PRIMAL_SPELLS: Spell[] = [
  // ======================== NIVEAU 1 ========================
  {
    id: 'pri-001',
    name: 'Enchevêtrement',
    school: 'primal',
    level: 1,
    manaCost: 2,
    castTime: '1 action',
    range: '27m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Des lianes, racines et ronces jaillissent du sol pour saisir et entraver toutes les creatures dans la zone. La vegetation s\'anime avec une volonte propre, s\'enroulant autour des chevilles et des membres avec une force surprenante.',
    effect: 'Zone de 6m de rayon devient un terrain difficile. Chaque creature dans la zone effectue un JdS FOR ou est entravee. Les creatures entravees peuvent utiliser une action pour retenter le JdS. La zone persiste meme sur sol nu.',
    classes: ['Druide', 'Rodeur', 'Gardien de la Foret'],
    synergy: 'Combine avec Appel de la Foudre pour frapper des cibles immobilisees.',
    lore: 'L\'Enchevetrement est le premier sort que les druides de la Foret d\'Yggdrasylve apprennent. La foret elle-meme leur enseigne, disent-ils, en guidant les lianes vers ceux qui menacent l\'equilibre naturel.'
  },
  {
    id: 'pri-002',
    name: 'Communication avec les Animaux',
    school: 'primal',
    level: 1,
    manaCost: 1,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide ouvre son esprit aux voix de la nature. Les cris des oiseaux deviennent des mots, les grognements des ours des phrases, et meme le bourdonnement des insectes porte un sens. La communication est limitee par l\'intelligence de l\'animal.',
    effect: 'Permet de communiquer avec les betes pendant la duree. Les animaux peuvent partager des informations sur les environs, les creatures, les dangers passes ou les predateurs. Attitude de base neutre, modifiable par CHA.',
    classes: ['Druide', 'Rodeur', 'Barde'],
    synergy: 'Avant Invocation de Compagnon Animal pour etablir un lien avec le compagnon.',
    lore: 'Les Murmure-Betes de la Foret d\'Yggdrasylve parlent avec les animaux aussi naturellement qu\'avec les humains. Ils servent de mediateurs entre les civilisations et le monde sauvage, un role vital pour l\'equilibre d\'Aethelgard.'
  },
  {
    id: 'pri-003',
    name: 'Baies Nourricières',
    school: 'primal',
    level: 1,
    manaCost: 1,
    castTime: '1 action',
    range: 'Contact',
    duration: '24 heures',
    components: ['Verbal', 'Somatique', 'Materiel (un brin de gui)'],
    description: 'Le druide insuffle l\'energie vitale de la nature dans une poignee de baies, les transformant en fruits magiques luminescents. Chaque baie brille d\'une lueur verte douce et degage un parfum de foret apres la pluie.',
    healing: '1 PV par baie (10 baies)',
    effect: 'Cree 10 baies magiques. Chaque baie soigne 1 PV et nourrit une creature pour une journee. Les baies perdent leur magie apres 24 heures. Maximum 10 baies actives par lanceur.',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Fourniture de nourriture pour les expeditions en territoire sauvage.',
    lore: 'Les Baies Nourricières sont un don de la Foret d\'Yggdrasylve, le coeur vert d\'Aethelgard. Les druides les distribuent aux voyageurs qui respectent la nature, et les refusent a ceux qui la pillent.'
  },
  {
    id: 'pri-004',
    name: 'Vague Tonnante',
    school: 'primal',
    level: 1,
    manaCost: 3,
    castTime: '1 action',
    range: 'Personnel (cube de 4,5m)',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide frappe le sol et une onde de choc primale se propage dans toutes les directions, repoussant tout ce qui se trouve sur son passage. Le sol tremble, les arbres plient, et les creatures sont projetees en arriere.',
    damage: '2d8 tonnerre',
    effect: 'Toute creature dans un cube de 4,5m autour du lanceur effectue un JdS CON. En cas d\'echec : 2d8 degats tonnerre et repoussee de 3m. En cas de reussite : demi-degats, non repoussee. Les objets non fixes sont repousses de 3m.',
    higherLevels: '+1d8 degats par niveau au-dela du 1er.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Repousse les ennemis dans un Enchevetrement.',
    lore: 'La Vague Tonnante canalise la force brute de la terre elle-meme. Les Gardiens de la Foret l\'utilisent pour repousser les bucherons qui s\'aventurent trop pres du coeur d\'Yggdrasylve.'
  },

  // ======================== NIVEAU 2 ========================
  {
    id: 'pri-005',
    name: 'Croissance d\'Epines',
    school: 'primal',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: '45m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (sept epines pointues)'],
    description: 'Le sol se herisse d\'epines vegetales dures comme l\'acier, transformant la zone en un piege vegetal mortel. Les epines poussent en un clin d\'oeil, s\'entremelant pour former un tapis dense de pointes acerées.',
    damage: '2d4 percant par 1,5m de deplacement',
    effect: 'Zone de 6m de rayon. Terrain difficile. Les creatures se deplacant dans la zone subissent 2d4 degats percants par 1,5m de deplacement. Le terrain est camouflage et ressemble au sol naturel (jet de Perception DD 15 pour detecter).',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Devant un Enchevetrement pour doubler les pieges de controle de zone.',
    lore: 'Les guerriers des forets combinent la Croissance d\'Epines avec des tactiques d\'embuscade. Les sentiers d\'Yggdrasylve sont parsemes de tels pieges, rendant la foret impenetrable aux envahisseurs.'
  },
  {
    id: 'pri-006',
    name: 'Invocation de Compagnon Animal',
    school: 'primal',
    level: 2,
    manaCost: 5,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (une touffe de fourrure)'],
    description: 'Le druide appelle un esprit animal qui se materialise sous une forme corporelle. L\'animal invoque est un esprit de la nature prenantune apparence physique, et il sert loyalement le druide pendant la duree du sort.',
    effect: 'Invoque un esprit animal de FP 2 ou moins. L\'animal agit a son propre tour et obeit aux ordres du lanceur (action bonus). Il a les stats d\'un animal normal mais avec des PV temporaires egaux au double du niveau du lanceur.',
    higherLevels: 'Au niveau 4+, FP 4 ou moins. Au niveau 6+, FP 6 ou moins.',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Communication avec les Animaux permet de donner des ordres complexes.',
    lore: 'Les compagnons animaux des druides d\'Aethelgard ne sont pas de simples betes — ce sont des esprits de la nature qui choisissent de servir. Le lien entre druide et compagnon est sacre, et le briser est considere comme une trahison envers la foret.'
  },
  {
    id: 'pri-007',
    name: 'Peau d\'Ecorce',
    school: 'primal',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (une poignee d\'ecorce de chene)'],
    description: 'La peau de la creature touchee se durcit et prend la texture de l\'ecorce d\'un arbre ancien. La transformation est subtile mais efficace — la peau reste souple tout en offrant une protection comparable a une armure intermediaire.',
    effect: 'La CA de la cible ne peut etre inferieure a 16, quel que soit l\'armure portee. Les degats contondants sont reduits de 2 points.',
    classes: ['Druide', 'Rodeur', 'Gardien de la Foret'],
    synergy: 'Combine avec Forme Bestiale pour une forme animale blindee.',
    lore: 'La Peau d\'Ecorce est un don des Ents d\'Yggdrasylve, les arbres-gardiens qui veillent sur la foret depuis l\'Ere des Sceaux. Les druides qui portent cette benediction sont consideres comme adoptes par la foret.'
  },
  {
    id: 'pri-008',
    name: 'Bourrasque',
    school: 'primal',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: 'Personnel (ligne de 18m)',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (une graine de pissenlit)'],
    description: 'Le druide souffle et un vent violent se leve, balayant tout sur son passage. La bourrasque est un mur de vent horizontal qui repousse les creatures, dissipe les gaz et devie les projectiles.',
    effect: 'Ligne de 18m x 3m. Les creatures dans la zone effectuent un JdS FOR ou sont repoussees de 4,5m et tombent a terre. Dissipe les gaz et brouillards. Les attaques a distance a travers la zone ont un desavantage. Maintenu chaque tour avec une action.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Dissipe les nuages de poison. Repousse vers Croissance d\'Epines.',
    lore: 'Les maitres du vent de la cote nord d\'Aethelgard utilisent la Bourrasque pour proteger les villages de peche contre les tempetes. Ils pretendent que le vent est un esprit vivant qui repond a ceux qui le respectent.'
  },

  // ======================== NIVEAU 3 ========================
  {
    id: 'pri-009',
    name: 'Appel de la Foudre',
    school: 'primal',
    level: 3,
    manaCost: 8,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide leve les bras et les nuages s\'assombrissent. A son commandement, des eclairs zebrent le ciel et frappent les points qu\'il designe. Si l\'orage est deja present, le sort est amplifie par la tempete naturelle.',
    damage: '3d10 foudre',
    effect: 'A chaque tour (action), un eclair frappe un point a portee. Toutes les creatures dans un rayon de 1,5m effectuent un JdS DEX pour demi-degats. Si le temps est orageux, les degats passent a 4d10.',
    higherLevels: '+1d10 degats par niveau au-dela du 3e.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Apres Enchevetrement, les cibles immobilisees ne peuvent pas esquiver.',
    lore: 'L\'Appel de la Foudre est la voix courroucee de la nature. Les druides des hauts plateaux l\'utilisent pour defendre les sommets sacres, et les orages au-dessus des montagnes d\'Aethelgard sont parfois l\'oeuvre d\'un druide en colere.'
  },
  {
    id: 'pri-010',
    name: 'Forme Bestiale',
    school: 'primal',
    level: 3,
    manaCost: 7,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide puise dans le lien primal qui l\'unit aux creatures sauvages et son corps se transforme. Les os craquent et se reforment, la peau s\'epaissit ou se couvre de fourrure, et en quelques secondes, une bete feroce se tient la ou il se trouvait.',
    effect: 'Le druide se transforme en bete de FP 3 ou moins. Adopte les stats physiques de la bete mais conserve INT, SAG, CHA. Si les PV de la bete tombent a 0, le druide reprend sa forme avec ses PV restants. Peut lancer des sorts simples en forme animale.',
    higherLevels: 'Au niveau 5+, FP 5. Au niveau 7+, FP 7 et formes elementaires.',
    classes: ['Druide'],
    synergy: 'Peau d\'Ecorce avant la transformation pour une forme bestiale blindee.',
    lore: 'La Forme Bestiale est l\'art sacre des Changepeau d\'Yggdrasylve. Chaque druide possede une forme de predilection, souvent liee a un souvenir ou un moment spirituel. Les Anciens pouvaient maintenir des formes animales pendant des annees.'
  },
  {
    id: 'pri-011',
    name: 'Mur de Vent',
    school: 'primal',
    level: 3,
    manaCost: 7,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (un petit eventail et une plume)'],
    description: 'Un mur de vent tourbillonnant se dresse a l\'endroit designe, creant une barriere quasi impenetrable pour les projectiles et les creatures volantes. Le rugissement du vent est assourdissant et les debris volent dans tous les sens.',
    effect: 'Mur de 15m de long, 4,5m de haut, 30cm d\'epaisseur. Les creatures de taille P ou moins ne peuvent le traverser. Les attaques a distance sont deviees. Les gaz et brouillards sont dissipes. Les creatures volantes sont repoussees (JdS FOR).',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Protection contre les archers pendant que Appel de la Foudre frappe.',
    lore: 'Les druides cotiers d\'Aethelgard maitrisent les Murs de Vent mieux que quiconque. Lors de l\'invasion maritime de Havrebrume, un cercle de druides a erige un mur de vent autour du port, rendant impossible tout tir de siege depuis les navires.'
  },
  {
    id: 'pri-012',
    name: 'Croissance Vegetale',
    school: 'primal',
    level: 3,
    manaCost: 6,
    castTime: '1 action ou 8 heures',
    range: '45m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'La vegetation environnante explose en une croissance luxuriante et acceleree. En un instant, les buissons deviennent des fourres impenetrables, les herbes des prairies hautes, et les arbustes des bosquets denses.',
    effect: 'Version rapide (1 action) : zone de 30m de rayon, la vegetation devient epaisse et toute la zone devient un terrain super-difficile (4x le cout de deplacement). Version lente (8 heures) : zone de 800m de rayon, fertilise la terre et double les recoltes pour 1 an.',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Zone de controle massive. Combine avec Enchevetrement dans la zone epaissie.',
    lore: 'La Croissance Vegetale est le pouvoir regenerateur de la nature rendu instantane. Les druides l\'utilisent aussi bien en combat qu\'en paix — pour bloquer les envahisseurs ou pour guerir les terres ravagees par la guerre.'
  },

  // ======================== NIVEAU 4 ========================
  {
    id: 'pri-013',
    name: 'Invocation d\'Elementaire',
    school: 'primal',
    level: 4,
    manaCost: 12,
    castTime: '1 minute',
    range: '27m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (element correspondant : terre, eau, feu ou air)'],
    description: 'Le druide ouvre un canal vers les plans elementaires et une forme se materialise, tiree de l\'element brut. L\'elementaire invoque est une incarnation de la nature primordiale, puissant et loyal envers celui qui l\'a appele.',
    effect: 'Invoque un elementaire de FP 5 ou moins (terre, eau, feu ou air). L\'elementaire agit a son tour et obeit aux ordres (action bonus). Si la concentration est brisee, l\'elementaire devient hostile pendant 1 minute avant de disparaitre.',
    higherLevels: 'Au niveau 6+, FP 7. Au niveau 8+, FP 9.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Elementaire d\'eau + Appel de la Foudre = bonus de degats foudre sur cibles mouillees.',
    lore: 'Les Elementalistes d\'Aethelgard sont les gardiens des quatre equilibres. Chaque druide a une affinite naturelle pour un element, et les plus sages apprennent a les maitriser tous. Les elementaires invoques conservent un lien avec leur plan d\'origine.'
  },
  {
    id: 'pri-014',
    name: 'Tempete de Grele',
    school: 'primal',
    level: 4,
    manaCost: 11,
    castTime: '1 action',
    range: '90m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (une pincee de poussiere et quelques gouttes d\'eau)'],
    description: 'Des nuages noirs s\'amassent instantanement et un deluge de grelons durs comme la pierre s\'abat sur la zone designee. Le sol est martele, les arbres ploient, et tout ce qui se trouve en dessous est ecrase par la fureur de la tempete.',
    damage: '2d8 contondant + 4d6 froid',
    effect: 'Zone de 6m de rayon en cylindre de 12m de haut. JdS DEX pour demi-degats. La zone devient un terrain difficile jusqu\'a la fin du prochain tour du lanceur. Les plantes non magiques sont detruites dans la zone.',
    higherLevels: '+1d8 contondant par niveau au-dela du 4e.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Les cibles dans Enchevetrement ne peuvent pas esquiver la grele.',
    lore: 'La Tempete de Grele est l\'arme des druides de guerre, capable de ravager des formations entieres. Les Seigneurs des Tempetes de la cote ouest la declenchent pour proteger les recifs sacres des flottes de peche excessives.'
  },
  {
    id: 'pri-015',
    name: 'Gardien de la Nature',
    school: 'primal',
    level: 4,
    manaCost: 10,
    castTime: '1 action',
    range: '9m',
    duration: 'Concentration, 8 heures',
    components: ['Verbal', 'Somatique'],
    description: 'Un arbre, un rocher ou une formation vegetale s\'anime et prend vie, devenant un gardien vegetal de taille G. L\'entite se dresse, ses branches devenant des bras, ses racines des jambes, et elle veille sur la zone avec une patience infinie.',
    effect: 'Anime un element naturel en gardien (CA 15, 60 PV, 2 attaques : +7, 2d6+4 contondant). Le gardien est immobile mais attaque toute creature hostile dans un rayon de 9m. Peut recevoir des ordres simples. Disparait a la fin du sort.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Place au centre d\'un Enchevetrement pour un piege avec gardien.',
    lore: 'Les Gardiens de la Nature sont les echos des Ents primordiaux qui peuplaient Aethelgard avant les civilisations. Chaque gardien anime conserve une parcelle de conscience vegetale, et certains refusent d\'attaquer les druides ennemis.'
  },
  {
    id: 'pri-016',
    name: 'Domination de Bete',
    school: 'primal',
    level: 4,
    manaCost: 12,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide projette sa volonte dans l\'esprit d\'une bete, ecrasant ses instincts et imposant ses propres ordres. L\'animal est completement soumis, ses yeux devenant vides et vitreux tandis que le druide le dirige comme une marionnette.',
    effect: 'La bete effectue un JdS SAG. En cas d\'echec, le druide en prend le controle total. Peut percevoir a travers ses sens (action). La bete repete le JdS a chaque fois qu\'elle subit des degats. Intelligence maximale de la cible : 4.',
    higherLevels: 'Au niveau 6+, duree 10 minutes. Au niveau 8+, duree 1 heure.',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Apres Communication avec les Animaux pour evaluer une bete avant de la dominer.',
    lore: 'La Domination de Bete est un pouvoir controverse parmi les druides. Le Cercle de l\'Equilibre la considere comme une violation du lien sacre entre l\'homme et la bete, tandis que le Cercle de la Guerre la voit comme un outil necessaire.'
  },

  // ======================== NIVEAU 5 ========================
  {
    id: 'pri-017',
    name: 'Eveil',
    school: 'primal',
    level: 5,
    manaCost: 16,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (une agate d\'une valeur de 1000 po, consomme)'],
    description: 'Le druide touche un animal ou une plante et lui confere le don de conscience. L\'intelligence fleurit dans l\'esprit de la creature, les yeux s\'eclairent de comprehension, et pour la premiere fois, elle pense veritablement.',
    effect: 'L\'animal ou la plante gagne une INT de 10 et la capacite de parler une langue. L\'animal est charme par le lanceur pendant 30 jours ou jusqu\'a ce que le lanceur lui fasse du mal. Apres, l\'animal choisit librement ses actions.',
    classes: ['Druide'],
    synergy: 'Cree un allie permanent intelligent avec Communication avec les Animaux.',
    lore: 'L\'Eveil est considere comme le don le plus sacre des druides. Les Ents d\'Yggdrasylve seraient des arbres eveilles il y a des millenaires. La Foret Parlante, au coeur d\'Yggdrasylve, serait entierement composee d\'arbres eveilles.'
  },
  {
    id: 'pri-018',
    name: 'Mur d\'Epines',
    school: 'primal',
    level: 5,
    manaCost: 14,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (une poignee d\'epines)'],
    description: 'Un mur massif de ronces entremelees jaillit du sol, ses epines aussi longues que des dagues et dures comme l\'acier. Le mur est si dense qu\'il bloque la vue et le passage, et toute tentative de le traverser est une epreuve sanglante.',
    damage: '7d8 percant (traversee)',
    effect: 'Mur de 18m de long, 3m d\'epaisseur, 3m de haut. Bloque la vision. Les creatures entrant ou commencant leur tour dans le mur subissent 7d8 degats percants. Traverser coute 4x le deplacement normal. JdS DEX pour demi-degats.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Piege les ennemis entre Mur d\'Epines et Appel de la Foudre.',
    lore: 'Le Mur d\'Epines est la barriere ultime de la nature. Les druides l\'utilisent pour proteger les bosquets sacres, et les murs les plus anciens ont evolue en ecosystemes autonomes, abritant des oiseaux et des insectes en leur sein.'
  },
  {
    id: 'pri-019',
    name: 'Controle des Vents',
    school: 'primal',
    level: 5,
    manaCost: 15,
    castTime: '1 action',
    range: '90m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide prend le controle des vents dans une vaste zone, dirigeant les courants aeriens selon sa volonte. Il peut creer des tempetes, des zones de calme, ou des corridors de vent favorables aux voyageurs.',
    effect: 'Controle le vent dans un cube de 30m. Peut creer : calme (annule le vent), brise (avantage/desavantage aux projectiles), tempete (terrain difficile, desavantage a la Perception auditive, eteint les flammes), ouragan (creatures TG ou moins repoussees, JdS FOR).',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Amplifier en tempete avant Appel de la Foudre pour les degats bonus.',
    lore: 'Les Seigneurs des Vents sont les druides les plus respectes des marins d\'Aethelgard. Leur capacite a calmer ou invoquer le vent determine le succes des voyages maritimes, et ils sont traites comme des invites d\'honneur sur tout navire.'
  },
  {
    id: 'pri-020',
    name: 'Fleaux d\'Insectes',
    school: 'primal',
    level: 5,
    manaCost: 14,
    castTime: '1 action',
    range: '90m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un morceau de sucre)'],
    description: 'Un essaim immense d\'insectes grouillants se materialise et envahit la zone designee. Les creatures prises dans l\'essaim sont mordues, piquees et assaillies par des milliers de mandibules, rendant toute concentration impossible.',
    damage: '4d10 percant par tour',
    effect: 'Sphere de 6m de rayon. Terrain difficile. Visibilite reduite. Les creatures commencant leur tour dans la zone subissent 4d10 degats percants (JdS CON pour demi-degats). Les lanceurs de sorts dans la zone ont un desavantage aux jets de Concentration.',
    classes: ['Druide'],
    synergy: 'Force les ennemis a fuir vers des Croissances d\'Epines ou Murs d\'Epines.',
    lore: 'Le Fleau d\'Insectes est le cauchemar des armees. Les druides de guerre d\'Aethelgard l\'utilisent pour briser les formations ennemies, et la simple rumeur de sa presence suffit parfois a mettre en deroute des troupes superstitieuses.'
  },

  // ======================== NIVEAU 6 ========================
  {
    id: 'pri-021',
    name: 'Marche dans les Arbres',
    school: 'primal',
    level: 6,
    manaCost: 18,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide fusionne avec un arbre et peut se deplacer instantanement d\'arbre en arbre, surgissant du tronc de l\'un pour plonger dans un autre. Le voyage est instantane et silencieux, comme si la foret elle-meme transportait le druide.',
    effect: 'Le druide entre dans un arbre et peut se teleporter vers un autre arbre de la meme espece a 150m. Peut utiliser cette teleportation une fois par tour. Le druide est invisible et invulnerable tant qu\'il est a l\'interieur d\'un arbre.',
    classes: ['Druide', 'Rodeur'],
    synergy: 'Ideal pour positionner Appel de la Foudre depuis differents angles.',
    lore: 'La Marche dans les Arbres est le secret des messagers de la foret. Le reseau d\'arbres d\'Yggdrasylve est si dense que les druides peuvent traverser la foret entiere en quelques minutes, emergant la ou on les attend le moins.'
  },
  {
    id: 'pri-022',
    name: 'Mur de Pierre Vivante',
    school: 'primal',
    level: 6,
    manaCost: 20,
    castTime: '1 action',
    range: '36m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un petit bloc de granit)'],
    description: 'Le sol se souleve et se plie, formant un mur massif de roche solide. Le mur n\'est pas inerte — il est imbu de l\'esprit de la terre et peut lentement s\'adapter pour combler les breches et repousser les intrusions.',
    effect: 'Mur de 30m de long, 6m de haut, 30cm d\'epaisseur (ou 10 panneaux de 3m). CA 15, 30 PV par panneau. Si un panneau est detruit, les panneaux adjacents se ferment lentement (1 tour). Peut etre faconne en formes variees (dome, cercle, etc.).',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Encercle les ennemis avant Appel de la Foudre ou Fleaux d\'Insectes.',
    lore: 'Les architectes druidiques de Coeurfer utilisent la Pierre Vivante pour construire des fortifications qui s\'auto-reparent. Les murs de la citadelle naine, dit-on, sont en partie composes de pierres animees par des druides allies il y a des siecles.'
  },
  {
    id: 'pri-023',
    name: 'Guerison Primale',
    school: 'primal',
    level: 6,
    manaCost: 22,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide canalise la force regeneratrice de la nature elle-meme. Des lianes luminescentes s\'enroulent autour de la creature blessee, des fleurs eclosent sur les plaies, et l\'energie vitale de la terre afflue dans le corps meurtri.',
    healing: '70 PV',
    effect: 'Soigne 70 PV. Met fin a la cecite, la surdite, toute maladie et tout empoisonnement. Si la creature a perdu un membre dans les dernieres 24 heures, le membre repousse en 2 minutes.',
    classes: ['Druide'],
    synergy: 'Apres une Forme Bestiale qui a ete vaincue, soigne la forme humaine.',
    lore: 'La Guerison Primale est la manifestation du cycle eternel de la vie et de la mort. Les druides guerisseurs d\'Yggdrasylve sont recherches dans tout Aethelgard, car leur art surpasse parfois meme celui des pretres de Solarius.'
  },
  {
    id: 'pri-024',
    name: 'Invocation de Meute',
    school: 'primal',
    level: 6,
    manaCost: 20,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un os de predateur)'],
    description: 'Le druide pousse un cri sauvage et une meute d\'esprits animaux se materialise, prets a chasser. Les betes invoquees agissent en coordination parfaite, encerclant et harcelant leurs proies avec une intelligence tactique surnaturelle.',
    effect: 'Invoque 8 betes de FP 1 ou moins, 4 betes de FP 2, ou 2 betes de FP 4. Les betes agissent immediatement apres le lanceur et obeissent a ses ordres. Elles attaquent en meute (+2 attaque par allie adjacent a la cible).',
    classes: ['Druide', 'Rodeur'],
    synergy: 'La meute pousse les ennemis vers les pieges de zone du druide.',
    lore: 'L\'Invocation de Meute est le cri de guerre des druides chasseurs. La Meute Spectrale, comme l\'appellent les villageois, est crainte par tous les braconniers d\'Aethelgard, car elle traque sans relache ceux qui offensent la nature.'
  },

  // ======================== NIVEAU 7 ========================
  {
    id: 'pri-025',
    name: 'Tempete Devastatrice',
    school: 'primal',
    level: 7,
    manaCost: 28,
    castTime: '1 action',
    range: '90m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide invoque une tempete cataclysmique qui combine les quatre elements dans un tourbillon destructeur. La pluie tombe horizontalement, la foudre frappe en continu, la grele martele tout, et le vent arrache les toits.',
    damage: '2d6 contondant + 2d6 foudre + 2d6 froid par tour',
    effect: 'Zone de 18m de rayon en cylindre de 12m. Terrain super-difficile. Visibilite nulle. Chaque tour, les creatures dans la zone subissent 2d6 contondant (vent), 2d6 foudre et 2d6 froid (JdS DEX pour demi-degats au froid). Le lanceur peut diriger un eclair bonus (5d10) chaque tour.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'A l\'interieur de la tempete, Appel de la Foudre obtient les degats bonus d\'orage.',
    lore: 'La Tempete Devastatrice est la colere de la nature personifiee. Les Anciens Druides pouvaient maintenir des tempetes pendant des jours, transformant des vallees entieres en zones de devastation. C\'est pourquoi les civilisations respectent — et craignent — les druides.'
  },
  {
    id: 'pri-026',
    name: 'Regeneration',
    school: 'primal',
    level: 7,
    manaCost: 26,
    castTime: '1 minute',
    range: 'Contact',
    duration: '1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un moulin a priere et de l\'eau benite)'],
    description: 'Le pouvoir regenerateur de la nature s\'installe dans le corps de la creature touchee. Les blessures se ferment a vue d\'oeil, les os se ressoudent, et meme les membres tranches commencent a repousser lentement.',
    healing: '1 PV par tour + regeneration de membres',
    effect: 'La cible regagne 1 PV au debut de chaque tour pendant 1 heure (total : 600 PV potentiels). Les membres severes repoussent en 2 minutes. La creature ne peut pas mourir de perte de sang tant que le sort est actif.',
    classes: ['Druide'],
    synergy: 'Avec Peau d\'Ecorce, la cible est quasi unkillable — se soigne plus vite qu\'on ne la blesse.',
    lore: 'La Regeneration est le secret des trolls et des hydres, apprivoise par les druides. Le Grand Druide Oakenshield aurait regenere un bras tranche en plein combat, continuant a se battre comme si de rien n\'etait.'
  },
  {
    id: 'pri-027',
    name: 'Forme Elementaire',
    school: 'primal',
    level: 7,
    manaCost: 30,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide transcende sa forme mortelle pour devenir un elementaire pur. Son corps se dissout et se reconstitue en terre, eau, feu ou air, une incarnation de la nature primordiale dans sa forme la plus brute et la plus puissante.',
    effect: 'Transformation en elementaire de FP 10 ou moins. Adopte toutes les stats de l\'elementaire sauf INT, SAG, CHA. Immunites elementaires selon le type. Si les PV de l\'elementaire tombent a 0, le druide reprend sa forme normale.',
    classes: ['Druide'],
    synergy: 'Forme de Feu + Appel de la Foudre pour un druide de combat elementaire devastateur.',
    lore: 'La Forme Elementaire est la voie de l\'Ascension druidique. Les Archidruides d\'Yggdrasylve passent des annees sous forme elementaire, communiant avec les forces primordiales. Certains ne reviennent jamais, choisissant l\'eternite en tant qu\'elementaire.'
  },
  {
    id: 'pri-028',
    name: 'Inversion de Terrain',
    school: 'primal',
    level: 7,
    manaCost: 26,
    castTime: '1 action',
    range: '90m',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide remodele le terrain a sa volonte, transformant radicalement le paysage. Les collines s\'aplanissent, les fosses se creusent, les forets poussent en un instant, et les rivieres changent de cours.',
    effect: 'Transforme le terrain dans un rayon de 45m. Options : creer/supprimer des fosses (6m de profondeur), elever/abaisser le terrain de 6m, faire pousser/disparaitre de la vegetation dense, creer/assecher un plan d\'eau. Les structures ne sont pas affectees.',
    classes: ['Druide', 'Gardien de la Foret'],
    synergy: 'Creer un terrain favorable avant Tempete Devastatrice.',
    lore: 'L\'Inversion de Terrain est l\'art des Faconneurs de Monde, un ordre druidique ancien qui aurait aide a sculpter les paysages d\'Aethelgard. Les Plaines du Titan, dit-on, furent creees par un seul Faconneur en une nuit.'
  },

  // ======================== NIVEAU 8 ========================
  {
    id: 'pri-029',
    name: 'Seisme',
    school: 'primal',
    level: 8,
    manaCost: 36,
    castTime: '1 action',
    range: '150m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (une pincee de terre, un morceau de roche et un grain de sable)'],
    description: 'Le druide frappe le sol et la terre entiere semble repondre. Le sol se fissure, les batiments s\'effondrent, et des crevasses s\'ouvrent, avalant tout ce qui s\'y trouve. C\'est la puissance brute de la terre dechainee.',
    damage: '6d10 contondant (structures), variable (creatures)',
    effect: 'Zone de 30m de rayon. A chaque tour, les creatures debout effectuent un JdS DEX ou tombent a terre et subissent 2d6 contondant. Des fissures s\'ouvrent (JdS DEX ou chute de 1d4 x 3m). Les structures subissent 6d10 degats par tour et peuvent s\'effondrer.',
    classes: ['Druide'],
    synergy: 'Les creatures dans les fissures ne peuvent pas echapper aux sorts de zone.',
    lore: 'Le Seisme est le cri de la terre, une force que meme les druides les plus puissants hesitent a dechainer. Le Seisme de Coeurfer, au Deuxieme Age, a ouvert les mines qui ont fait la fortune des nains, mais aussi les tunnels qui ont laisse entrer les creatures de l\'Ombre.'
  },
  {
    id: 'pri-030',
    name: 'Tsunami',
    school: 'primal',
    level: 8,
    manaCost: 38,
    castTime: '1 minute',
    range: 'Ligne de vue',
    duration: 'Concentration, 6 rounds',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide leve les bras et les eaux repondent. Une vague titanesque se dresse, haute de plusieurs dizaines de metres, et s\'abat sur le rivage avec une force devastatrice. Tout ce qui se trouve sur son passage est emporte.',
    damage: '6d10 contondant (diminuant de 1d10 par round)',
    effect: 'Mur d\'eau de 90m de long et 90m de haut. Avance de 15m par round. Les creatures touchees effectuent un JdS FOR ou subissent 6d10 contondant et sont emportees. Les degats diminuent de 1d10 par round. Les structures subissent des degats doubles.',
    classes: ['Druide'],
    synergy: 'Apres le tsunami, la zone inondee amplifie les sorts de foudre.',
    lore: 'Le Tsunami est l\'arme ultime des druides oceaniques. Lors de la defense de la Cote des Perles, un cercle de druides a invoque un tsunami qui a aneanti une flotte d\'invasion entiere, mais a egalement detruit trois villages cotiers.'
  },
  {
    id: 'pri-031',
    name: 'Forme de l\'Ancien',
    school: 'primal',
    level: 8,
    manaCost: 40,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un fragment de bois petrifie d\'Yggdrasylve)'],
    description: 'Le druide se transforme en un Ent ancien, un arbre-gardien de 12m de haut dont les racines plongent profondement dans la terre. Sous cette forme, il est un bastion de la nature, pratiquement indestructible et capable de commander la vegetation environnante.',
    effect: 'Transformation en Ent Ancien : CA 18, 250 PV, FOR 26, 2 attaques (3d10+8 contondant). Peut animer jusqu\'a 3 arbres proches comme treants. Immunite aux degats psychiques. Vulnerabilite au feu. Peut lancer des sorts druidiques.',
    classes: ['Druide'],
    synergy: 'Forme ideale pour maintenir la concentration sur Tempete Devastatrice.',
    lore: 'La Forme de l\'Ancien est la communion ultime avec la Foret d\'Yggdrasylve. Les Archidruides qui adoptent cette forme pretendent entendre la voix de la foret elle-meme, un murmure ancien qui porte les souvenirs de toutes les saisons depuis la creation.'
  },
  {
    id: 'pri-032',
    name: 'Controle Climatique',
    school: 'primal',
    level: 8,
    manaCost: 36,
    castTime: '10 minutes',
    range: '1,5 km',
    duration: 'Concentration, 8 heures',
    components: ['Verbal', 'Somatique', 'Materiel (encens brulant et un morceau de terre et bois)'],
    description: 'Le druide prend le controle du climat dans une zone immense, modifiant la temperature, le vent, les precipitations et tout autre phenomene meteorologique. Le ciel obeit a sa volonte pendant des heures.',
    effect: 'Controle total du climat dans un rayon de 1,5 km. Peut modifier progressivement (30 min par etape) : temperature (-20 a +30 degres), vent (calme a ouragan), precipitations (clair a tempete de neige/grele). Les changements extremes peuvent causer des degats environnementaux.',
    classes: ['Druide'],
    synergy: 'Creer un orage pour amplifier Appel de la Foudre pendant des heures.',
    lore: 'Le Controle Climatique est le pouvoir des Archidruides legendaires. On dit que le climat d\'Aethelgard etait autrefois entierement gere par un conseil de druides, maintenant les saisons en equilibre parfait — un art perdu depuis la Guerre des Sceaux.'
  },

  // ======================== NIVEAU 9 ========================
  {
    id: 'pri-033',
    name: 'Tempete Primordiale',
    school: 'primal',
    level: 9,
    manaCost: 45,
    castTime: '1 action',
    range: '300m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide invoque une tempete primordiale combinant tous les elements dans un cataclysme qui rappelle les forces qui ont forge Aethelgard. La terre tremble, le ciel se dechire, les eaux se soulevent et le feu pleut des cieux.',
    damage: '4d6 foudre + 4d6 froid + 4d6 contondant + 4d6 feu par tour',
    effect: 'Zone de 30m de rayon. Chaque tour, toutes les creatures : JdS DEX pour demi-degats (4 types de 4d6 chacun). Terrain impraticable. Visibilite nulle. Les batiments subissent des degats triples. Le lanceur peut diriger un eclair de 10d10 foudre par tour.',
    classes: ['Druide'],
    synergy: 'Apres Forme Elementaire de Tempete pour resister aux degats de sa propre tempete.',
    lore: 'La Tempete Primordiale est la nature dans sa forme la plus violente et la plus belle. Les anciens racontent que c\'est une telle tempete qui a faconne le continent d\'Aethelgard, et que l\'invoquer est un rappel du pouvoir originel du monde.'
  },
  {
    id: 'pri-034',
    name: 'Metamorphose Veritable',
    school: 'primal',
    level: 9,
    manaCost: 44,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (une goutte de mercure et un morceau de la creature cible)'],
    description: 'Le druide transforme une creature en n\'importe quelle autre creature. La transformation est si complete que meme l\'ame est temporairement reconfigurée. Un paysan peut devenir un dragon, un rat un geant — les limites de la nature sont transcendees.',
    effect: 'Transforme une creature en toute creature de FP egal ou inferieur a son niveau (ou FP original). Adopte toutes les stats de la nouvelle forme. Si les PV tombent a 0, la cible reprend sa forme. Si concentre 1 heure complete, la transformation est permanente.',
    classes: ['Druide'],
    synergy: 'Transformer un allie en dragon avant une bataille majeure.',
    lore: 'La Metamorphose Veritable est l\'art ultime des Changepeau. La legende raconte qu\'un Archidruide s\'est un jour transforme en montagne pour proteger une vallee, et que cette montagne est encore la aujourd\'hui.'
  },
  {
    id: 'pri-035',
    name: 'Jugement de la Nature',
    school: 'primal',
    level: 9,
    manaCost: 42,
    castTime: '1 action',
    range: '30m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le druide invoque le jugement de la nature elle-meme sur une creature qui a offense l\'equilibre naturel. La terre, l\'eau, l\'air et le feu convergent sur la cible, la consumant dans un vortex elementaire implacable.',
    damage: '20d8 (melange de tous les types elementaires)',
    effect: 'La cible effectue un JdS CON DD 21. En cas d\'echec : 20d8 degats (5d8 de chaque element). En cas de reussite : demi-degats. Les creatures qui ont detruit de la nature ou corrompu des elements subissent des degats doubles.',
    classes: ['Druide'],
    synergy: 'Combine avec Forme Elementaire pour lancer ce sort depuis une position invulnerable.',
    lore: 'Le Jugement de la Nature n\'est pas un acte de colere mais de justice. Le druide ne choisit pas la sentence — c\'est la nature elle-meme qui juge. Les creatures innocentes ou en harmonie avec la nature ne subissent que des degats legers.'
  },
  {
    id: 'pri-036',
    name: 'Sanctuaire de la Foret Eternelle',
    school: 'primal',
    level: 9,
    manaCost: 48,
    castTime: 'rituel 1h',
    range: '150m',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (une graine de l\'Arbre-Monde d\'Yggdrasylve)'],
    description: 'Le druide plante une graine sacree et une foret primordiale jaillit en quelques heures, creant un ecosysteme complet et auto-suffisant. La foret est imprégnee de magie primale et protege activement ses habitants.',
    effect: 'Cree une foret de 150m de rayon. La foret est un terrain difficile pour les ennemis mais normal pour les allies. Regenere 5 PV par tour pour les allies. Les arbres alertent le druide des intrus. La foret persiste indefiniment et croit naturellement.',
    classes: ['Druide'],
    synergy: 'Base parfaite pour Marche dans les Arbres et toutes les strategies de controle de zone.',
    lore: 'Le Sanctuaire de la Foret Eternelle est le leg ultime d\'un druide au monde. Chaque grande foret d\'Aethelgard aurait commence comme un tel sanctuaire, plante par un Archidruide des ages passes. Yggdrasylve elle-meme aurait ete le premier sanctuaire.'
  },

  // ======================== NIVEAU 10 ========================
  {
    id: 'pri-037',
    name: 'Eveil d\'Yggdrasylve',
    school: 'primal',
    level: 10,
    manaCost: 60,
    castTime: 'rituel 1h',
    range: '1,5 km',
    duration: 'Concentration, 1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (une feuille d\'or de l\'Arbre-Monde, artefact unique)'],
    description: 'Le druide invoque la conscience de la Foret d\'Yggdrasylve elle-meme, eveillant la plus ancienne et la plus puissante entite vegetale d\'Aethelgard. La terre tremble, les arbres s\'animent, et une intelligence millenniale embrasse toute la zone.',
    effect: 'Tous les arbres dans un rayon de 1,5 km s\'animent comme des treants. La foret devient un etre conscient qui obeit au druide. Les creatures dans la zone sont detectees automatiquement. Les ennemis subissent 6d10 contondant par tour (JdS DEX). Les allies sont gueris de 4d10 par tour.',
    classes: ['Druide'],
    synergy: 'Necessite une foret — combine avec Sanctuaire de la Foret Eternelle.',
    lore: 'L\'Eveil d\'Yggdrasylve est le miracle des Archidruides legendaires. On dit que la foret conserve une memoire de tout ce qui s\'est passe sous ses frondaisons, et que l\'eveiller, c\'est acceder a des milliers d\'annees de souvenirs. Le prix est lourd — le druide doit fusionner temporairement son esprit avec la foret.'
  },
  {
    id: 'pri-038',
    name: 'Cataclysme Elementaire',
    school: 'primal',
    level: 10,
    manaCost: 65,
    castTime: '1 action',
    range: '300m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un cristal contenant l\'essence des quatre elements, consomme)'],
    description: 'Le druide libere les quatre elements dans leur forme la plus pure et la plus destructrice. La terre se brise, les eaux deferlent, le feu consume tout, et le vent hurle. C\'est le pouvoir brut de la creation retourne contre elle-meme.',
    damage: '10d10 feu + 10d10 froid + 10d10 foudre + 10d10 contondant',
    effect: 'Zone de 24m de rayon. Chaque creature : JdS CON DD 23 pour demi-degats. Les quatre types de degats sont appliques separement (les resistances comptent pour chaque). La zone est transformee en terrain ravage pendant 1 an.',
    classes: ['Druide'],
    synergy: 'Sort de destruction totale — aucune synergie necessaire.',
    lore: 'Le Cataclysme Elementaire n\'a ete lance qu\'une fois dans l\'histoire d\'Aethelgard, par l\'Archidruide Galea lors de la chute du Sceau de la Mer. L\'explosion a cree le Gouffre de Corail, une cicatrice dans l\'ocean visible depuis l\'espace.'
  },
  {
    id: 'pri-039',
    name: 'Avatar de la Nature',
    school: 'primal',
    level: 10,
    manaCost: 70,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (la couronne de l\'Archidruide Primordial, artefact unique)'],
    description: 'Le druide transcende sa forme mortelle pour devenir l\'incarnation vivante de la nature. Son corps se transforme en un colosse vegetal et mineral de 15m de haut, une entite primordiale qui rappelle les premiers jours d\'Aethelgard.',
    effect: 'Transformation en Avatar de la Nature : CA 22, 400 PV, FOR 30, immunite aux degats non magiques. 3 attaques par tour (4d12+10). Peut lancer des sorts druidiques sans composantes. Controle la vegetation dans 60m. Apres : 5 niveaux d\'epuisement.',
    classes: ['Druide'],
    synergy: 'Sort ultime primal. Combine avec Tempete Primordiale pour un druide apocalyptique.',
    lore: 'L\'Avatar de la Nature est le druide devenu nature. L\'Archidruide Thorn est reste sous cette forme pendant un siecle pour proteger le coeur d\'Yggdrasylve, et quand il est finalement revenu a sa forme humaine, la foret a pleure.'
  },
  {
    id: 'pri-040',
    name: 'Renaissance du Monde',
    school: 'primal',
    level: 10,
    manaCost: 75,
    castTime: 'rituel 1h',
    range: '3 km',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (la derniere graine de l\'Arbre Originel, artefact legendaire, consomme)'],
    description: 'Le druide accomplit le miracle ultime : restaurer une zone devastee a son etat naturel originel. Les terres ravagees refleurrissent, les eaux polluees se purifient, les ecosystemes detruits se reconstruisent. C\'est un acte de creation pure.',
    effect: 'Restaure toute la nature dans un rayon de 3 km. Purifie toute corruption, malediction ou pollution. Regenere les ecosystemes detruits. Guerit toutes les creatures naturelles dans la zone a leurs PV max. Cree une zone de magie primale amplifiee permanente (+50% degats sorts primaux).',
    classes: ['Druide'],
    synergy: 'Peut restaurer les zones detruites par Apocalypse Arcanique ou corruption de l\'Ombre.',
    lore: 'La Renaissance du Monde est l\'espoir ultime d\'Aethelgard. Quand les Sceaux se briseront et que les tenebres devoreront le monde, les druides croient qu\'un Archidruide accomplira ce miracle pour faire naitre Aethelgard a nouveau. C\'est leur prophetie la plus sacree.'
  }
];
