// ============================================================================
// GRIMOIRE D'AETHELGARD - SORTS DIVINS
// Magie basee sur la foi, guerison, protection, lumiere sacree de Solarius
// ============================================================================

import { Spell } from './spells-arcane';

export const DIVINE_SPELLS: Spell[] = [
  // ======================== NIVEAU 1 ========================
  {
    id: 'div-001',
    name: 'Mot de Guerison',
    school: 'divine',
    level: 1,
    manaCost: 2,
    castTime: '1 action bonus',
    range: '18m',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le pretre prononce une priere de guerison et une lumiere doree enveloppe la creature blessee, refermant ses plaies les plus legeres. La chaleur divine se repand dans le corps, apaisant la douleur instantanement.',
    healing: '1d4+WIS',
    effect: 'Soigne une creature visible a portee de 1d4 + modificateur de Sagesse PV. Ne peut pas soigner les morts-vivants ni les constructs.',
    higherLevels: '+1d4 guerison par niveau au-dela du 1er.',
    classes: ['Pretre', 'Paladin', 'Gardien'],
    synergy: 'Peut etre lance en action bonus, permettant un sort offensif en action principale.',
    lore: 'Le Mot de Guerison est la premiere priere enseignee aux novices du Temple de Solarius. On dit que le dieu solaire murmure lui-meme les mots a l\'oreille de ses fideles, et que chaque guerison renforce le lien entre le pretre et sa divinite.'
  },
  {
    id: 'div-002',
    name: 'Bouclier de la Foi',
    school: 'divine',
    level: 1,
    manaCost: 2,
    castTime: '1 action bonus',
    range: '18m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un petit parchemin avec un texte sacre)'],
    description: 'Un champ de force scintillant entoure la creature protegee, emanant une douce lumiere doree. Le bouclier repousse les coups avec une force surnaturelle, guidee par la volonte divine de proteger les justes.',
    effect: '+2 a la CA de la cible pendant la duree. Le bouclier est visible comme une aura doree legere. Les morts-vivants subissent 1d4 degats radiants s\'ils touchent la cible protegee.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Combine avec Benediction pour un allie quasi invulnerable.',
    lore: 'Le Bouclier de la Foi est le symbole de la protection divine de Solarius. Les Chevaliers de l\'Aube portent ce bouclier en permanence, et on dit que sa lueur guide les voyageurs perdus dans les nuits les plus sombres d\'Aethelgard.'
  },
  {
    id: 'div-003',
    name: 'Benediction',
    school: 'divine',
    level: 1,
    manaCost: 3,
    castTime: '1 action',
    range: '9m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (aspersion d\'eau benite)'],
    description: 'Le pretre trace un signe sacre dans l\'air et une benediction divine descend sur ses compagnons. Chacun ressent une confiance surnaturelle, comme si une main invisible guidait leurs gestes et aiguisait leur esprit.',
    effect: 'Jusqu\'a 3 creatures ajoutent 1d4 a tous leurs jets d\'attaque et jets de sauvegarde pendant la duree.',
    higherLevels: '+1 creature supplementaire par niveau au-dela du 1er.',
    classes: ['Pretre', 'Paladin', 'Gardien'],
    synergy: 'Combine avec Bouclier de la Foi pour une defense et une offense ameliorees.',
    lore: 'La Benediction de Solarius est la priere la plus recitee dans les temples d\'Aethelgard. Avant chaque bataille, les pretres de campagne la prononcent sur les soldats, et nombreux sont ceux qui attribuent leur survie a cette grace divine.'
  },
  {
    id: 'div-004',
    name: 'Chatiment Sacre',
    school: 'divine',
    level: 1,
    manaCost: 3,
    castTime: '1 action bonus',
    range: 'Personnel',
    duration: '1 minute',
    components: ['Verbal'],
    description: 'L\'arme du paladin s\'illumine d\'un feu sacre, irradiant d\'une lumiere blanche purificatrice. Le prochain coup porte par cette arme frappe avec la force de la conviction divine, brulant les impies et les morts-vivants.',
    damage: '2d6 radiant (supplementaire a l\'attaque)',
    effect: 'La prochaine attaque de melee reussie inflige +2d6 degats radiants. +1d6 supplementaire contre les morts-vivants et les fielons. L\'arme emet une lumiere vive de 6m.',
    higherLevels: '+1d6 degats radiants par niveau au-dela du 1er.',
    classes: ['Paladin', 'Chevalier-Mage'],
    synergy: 'Apres Benediction, le bonus d\'attaque rend le chatiment plus fiable.',
    lore: 'Le Chatiment Sacre est la signature des Paladins de l\'Ordre de l\'Aube. Chaque coup porte avec cette priere est un acte de foi, et les plus fervents pretendent voir la main de Solarius guider leur lame.'
  },

  // ======================== NIVEAU 2 ========================
  {
    id: 'div-005',
    name: 'Restauration Mineure',
    school: 'divine',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le pretre pose ses mains sur la creature affligee et canalise l\'energie divine pour purifier son corps. Les poisons sont neutralises, les maladies repoussees, et les afflictions mineures dissipees par la lumiere purificatrice.',
    effect: 'Met fin a une maladie ou un etat parmi : aveugle, assourdi, empoisonne, paralyse. Neutralise un poison actif.',
    classes: ['Pretre', 'Paladin', 'Gardien', 'Druide'],
    synergy: 'Essentiel apres un combat contre des morts-vivants ou des creatures venimeuses.',
    lore: 'La Restauration est l\'art de guerison le plus sacre du Temple de Solarius. Les Guerisseurs Itinerants parcourent les villages d\'Aethelgard, offrant cette benediction aux malades et aux affliges sans distinction de rang ni de richesse.'
  },
  {
    id: 'div-006',
    name: 'Arme Spirituelle',
    school: 'divine',
    level: 2,
    manaCost: 4,
    castTime: '1 action bonus',
    range: '18m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Une arme spectrale faite de lumiere divine se materialise et flotte dans les airs, frappant les ennemis selon la volonte du pretre. L\'arme prend la forme du symbole sacre de la divinite du lanceur — un soleil radieux pour Solarius.',
    damage: '1d8+WIS force',
    effect: 'Cree une arme flottante qui attaque en action bonus. Deplacee de 6m et attaque une creature a son tour. L\'arme ne peut etre attaquee ni detruite.',
    higherLevels: '+1d8 degats par 2 niveaux au-dela du 2e.',
    classes: ['Pretre'],
    synergy: 'Permet d\'attaquer tout en maintenant Concentration sur un sort de soin.',
    lore: 'L\'Arme Spirituelle est l\'extension de la volonte divine. Les pretres-guerriers du Temple de Guerre manifestent des marteaux flamboyants, tandis que les pretres de Solarius invoquent des epees de lumiere pure.'
  },
  {
    id: 'div-007',
    name: 'Zone de Verite',
    school: 'divine',
    level: 2,
    manaCost: 5,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'Une sphere de lumiere sacree invisible s\'etend autour du lanceur. Toute creature dans cette zone ressent une pression divine sur son esprit, l\'empechant de proferer des mensonges deliberes.',
    effect: 'Zone de 4,5m de rayon. Les creatures dans la zone doivent reussir un JdS CHA ou etre incapables de mentir deliberement. Le lanceur sait quelles creatures ont reussi ou echoue leur sauvegarde.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Combine avec Clairvoyance pour un interrogatoire a distance.',
    lore: 'Les tribunaux d\'Aethelgard utilisent la Zone de Verite pour les proces importants. Le Temple de Solarius fournit des pretres certifies pour ce service, bien que les plus habiles menteurs aient appris a resister a la pression divine.'
  },
  {
    id: 'div-008',
    name: 'Flamme Sacree Persistante',
    school: 'divine',
    level: 2,
    manaCost: 4,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Des flammes blanches et or descendent du ciel sur la creature designee, brulant le mal sans consumer la chair. Les flammes sacrees persistent, marquant la cible d\'un sceau lumineux visible de tous.',
    damage: '2d8 radiant par tour',
    effect: 'La cible effectue un JdS DEX chaque tour. En cas d\'echec, elle subit 2d8 degats radiants et emet de la lumiere (pas d\'Invisibilite possible). Les morts-vivants ont un desavantage au JdS. Avantage aux attaques contre la cible marquee.',
    higherLevels: '+1d8 par niveau au-dela du 2e.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Marque la cible pour les attaques de Chatiment Sacre des paladins allies.',
    lore: 'La Flamme Sacree est le courroux de Solarius rendu visible. Les Inquisiteurs du Temple utilisent ce sort pour marquer les heretiques et les serviteurs de l\'Ombre, les rendant incapables de se dissimuler.'
  },

  // ======================== NIVEAU 3 ========================
  {
    id: 'div-009',
    name: 'Revigoration',
    school: 'divine',
    level: 3,
    manaCost: 7,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 300 po, consomme)'],
    description: 'Le pretre place ses mains sur le corps d\'une creature recemment decedee et canalise une puissante vague d\'energie divine. L\'ame du defunt est rappelee depuis les portes de l\'au-dela et reintegree dans son enveloppe charnelle.',
    healing: 'Revient a 1 PV',
    effect: 'Ramene a la vie une creature morte depuis moins d\'1 minute avec 1 PV. Ne fonctionne pas si la creature est morte de vieillesse, si son corps est detruit, ou si son ame est retenue. La creature subit -4 a tous les jets pendant 4 jours.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Combine avec Restauration Mineure pour soigner les sequelles de la mort.',
    lore: 'La Revigoration est un miracle sacre qui ne doit pas etre utilise a la legere. Le Temple de Solarius enseigne que chaque rappel de l\'au-dela derange l\'equilibre entre les vivants et les morts, et que l\'ame rappelee porte toujours un fragment de l\'Autre Cote.'
  },
  {
    id: 'div-010',
    name: 'Lueur d\'Espoir',
    school: 'divine',
    level: 3,
    manaCost: 7,
    castTime: '1 action',
    range: '9m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique'],
    description: 'Une lueur chaleureuse emane du pretre, enveloppant ses allies d\'une aura d\'espoir et de courage. Les blessures semblent moins graves, les poisons moins virulents, et chaque guerison produit des resultats remarquables.',
    effect: 'Jusqu\'a 6 creatures dans la zone obtiennent un avantage aux JdS contre la mort et recoivent le maximum de guerison de tout sort ou capacite de soin.',
    classes: ['Pretre', 'Gardien'],
    synergy: 'Maximise l\'effet de Mot de Guerison et toutes les guerisons du groupe.',
    lore: 'La Lueur d\'Espoir est la priere des heures les plus sombres. Lors du Siege de Solaureus, les pretres du Temple ont maintenu cette aura pendant trois jours consecutifs, permettant aux defenseurs blesses de continuer le combat.'
  },
  {
    id: 'div-011',
    name: 'Dissipation du Mal',
    school: 'divine',
    level: 3,
    manaCost: 8,
    castTime: '1 action',
    range: '9m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (eau benite et encens)'],
    description: 'Le pretre invoque le pouvoir purificateur de Solarius pour chasser les forces malignes. Une vague de lumiere sacree balaie la zone, brulant les enchantements sombres et repoussant les creatures des tenebres.',
    damage: '4d8 radiant (contre morts-vivants et fielons)',
    effect: 'Met fin a un enchantement, une possession ou une malediction sur une creature, OU inflige 4d8 degats radiants aux morts-vivants et fielons dans un rayon de 9m (JdS SAG pour demi-degats).',
    higherLevels: '+2d8 degats par niveau au-dela du 3e.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Combine avec Flamme Sacree Persistante pour purger les morts-vivants.',
    lore: 'La Dissipation du Mal est le rite de purification le plus puissant accessible aux pretres intermediaires. Les Exorcistes du Temple sont specialises dans cette priere, parcourant Aethelgard pour nettoyer les lieux corrompus.'
  },
  {
    id: 'div-012',
    name: 'Gardien Spirituel',
    school: 'divine',
    level: 3,
    manaCost: 8,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un symbole sacre)'],
    description: 'Des esprits gardiens lumineux se materialisent autour du pretre, tournoyant dans un ballet protecteur. Ces entites semi-transparentes prennent la forme d\'anges guerriers dores pour les fideles de Solarius.',
    damage: '3d8 radiant',
    effect: 'Les esprits occupent un rayon de 4,5m autour du lanceur. Toute creature hostile entrant dans la zone ou y commencant son tour subit 3d8 degats radiants (JdS SAG pour demi-degats). Les allies ne sont pas affectes.',
    higherLevels: '+1d8 degats par niveau au-dela du 3e.',
    classes: ['Pretre'],
    synergy: 'Combine avec Bouclier de la Foi pour un pretre quasi inattaquable au corps a corps.',
    lore: 'Les Gardiens Spirituels sont des fragments de la volonte divine qui protegent les fideles. Les pretres de guerre de Coeurfer les invoquent avant chaque charge, et les esprits lumineux sont devenus un symbole de bravoure dans les armees d\'Aethelgard.'
  },

  // ======================== NIVEAU 4 ========================
  {
    id: 'div-013',
    name: 'Restauration Majeure',
    school: 'divine',
    level: 4,
    manaCost: 10,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (poudre de diamant d\'une valeur de 100 po, consomme)'],
    description: 'Le pretre canalise une puissante energie divine pour restaurer completement le corps et l\'esprit d\'une creature. Les maledictions sont brisees, les afflictions purgees, et les capacites perdues restaurees.',
    effect: 'Met fin a un effet au choix : reduction de stat, malediction, petrification, charme/effroi, un niveau d\'epuisement. Restaure egalement les PV maximum reduits.',
    classes: ['Pretre', 'Gardien', 'Druide'],
    synergy: 'Indispensable apres un combat contre des creatures qui drainent l\'ame ou petrfient.',
    lore: 'La Restauration Majeure est un miracle qui exige une profonde connexion avec le divin. Les Grands Pretres du Temple passent des annees a perfectionner cette priere, car une erreur peut aggraver l\'affliction au lieu de la guerir.'
  },
  {
    id: 'div-014',
    name: 'Gardien de la Foi',
    school: 'divine',
    level: 4,
    manaCost: 10,
    castTime: '1 action',
    range: '9m',
    duration: '8 heures',
    components: ['Verbal'],
    description: 'Un gardien spectral de taille G se materialise dans un espace inoccupe. L\'entite divine, une figure en armure doree emanant une lumiere vive, monte une garde silencieuse et implacable, frappant tout ennemi qui s\'approche.',
    damage: '20 radiant',
    effect: 'Cree un gardien spectral immobile de taille G. Toute creature hostile terminant son tour dans un rayon de 3m subit 20 degats radiants (JdS DEX pour demi-degats). Le gardien disparait apres avoir inflige 60 degats au total.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Positionner pres de Gardien Spirituel pour une zone de mort radiant.',
    lore: 'Le Gardien de la Foi est l\'avatar miniature de la volonte protectrice de Solarius. Les temples d\'Aethelgard en placent aux portes pendant la nuit, et les voyageurs savent qu\'une lumiere doree a l\'entree d\'un lieu signifie protection et securite.'
  },
  {
    id: 'div-015',
    name: 'Bannissement',
    school: 'divine',
    level: 4,
    manaCost: 11,
    castTime: '1 action',
    range: '18m',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (un objet desagreable pour la cible)'],
    description: 'Le pretre prononce un decret divin d\'expulsion, et la creature ciblee est arrachee de ce plan d\'existence. Si elle est native d\'un autre plan, elle y est renvoyee ; si elle est native de ce plan, elle est envoyee dans un demi-plan inoffensif.',
    effect: 'La cible effectue un JdS CHA. En cas d\'echec, elle est bannie. Les creatures extraplanaires sont renvoyees dans leur plan d\'origine. Les natives vont dans un demi-plan inoffensif. Si la concentration dure 1 minute complete, le bannissement des extraplanaires est permanent.',
    higherLevels: '+1 creature supplementaire par niveau au-dela du 4e.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Contre les invocations de l\'ombre — bannit les morts-vivants et demons invoques.',
    lore: 'Le Bannissement est le jugement divin contre les intrus planaires. Les Exorcistes du Temple l\'utilisent comme arme ultime contre les demons et les entites de l\'Ombre qui s\'infiltrent dans Aethelgard a travers les fissures des Sceaux.'
  },
  {
    id: 'div-016',
    name: 'Aura de Vie',
    school: 'divine',
    level: 4,
    manaCost: 12,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal'],
    description: 'Une aura pulsante de lumiere doree emane du pretre, repoussant les griffes de la mort. Les allies proches sont maintenus en vie par la force de la foi, refusant de succomber tant que la lumiere brille.',
    healing: '1 PV par tour aux allies a 0 PV',
    effect: 'Aura de 9m de rayon. Les allies non-morts-vivants a 0 PV dans l\'aura regagnent 1 PV au debut de leur tour. Les creatures vivantes dans l\'aura ont resistance aux degats necrotiques.',
    classes: ['Pretre', 'Paladin', 'Gardien'],
    synergy: 'Avec Lueur d\'Espoir, les allies se relevent avec plus de PV.',
    lore: 'L\'Aura de Vie est la manifestation de la compassion de Solarius. Lors des grandes epidemies de plague d\'ombre, les pretres portant cette aura parcouraient les rues, repoussant la mort elle-meme par la seule force de leur foi.'
  },

  // ======================== NIVEAU 5 ========================
  {
    id: 'div-017',
    name: 'Resurrection',
    school: 'divine',
    level: 5,
    manaCost: 16,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 1000 po, consomme)'],
    description: 'Le pretre entreprend un long rituel sacre, appelant l\'ame du defunt a travers les voiles separant les vivants des morts. Si l\'ame est libre et consentante, elle reintegre son corps, qui guerit de ses blessures mortelles.',
    healing: 'PV maximum complets',
    effect: 'Ramene a la vie une creature morte depuis moins de 10 jours. Soigne toutes les blessures mortelles. Ne restaure pas les membres manquants. La creature subit -2 a tous les jets pendant 4 jours. L\'ame doit etre libre et consentante.',
    classes: ['Pretre'],
    synergy: 'Suivi de Restauration Majeure pour eliminer les penalites.',
    lore: 'La Resurrection est le plus grand miracle du Temple de Solarius. Elle n\'est accordee qu\'a ceux qui en sont dignes, et le Grand Pretre lui-meme doit approuver le rituel. On dit que chaque resurrection coute un fragment de la lumiere de Solarius.'
  },
  {
    id: 'div-018',
    name: 'Pilier de Flamme',
    school: 'divine',
    level: 5,
    manaCost: 14,
    castTime: '1 action',
    range: '18m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (une pincee de soufre)'],
    description: 'Une colonne de feu sacre descend des cieux, consumant les impies dans un brasier divin. Les flammes blanches et or ne brulent pas les fideles mais devoren les servants du mal avec une ferocite implacable.',
    damage: '4d6 feu + 4d6 radiant',
    effect: 'Cylindre de 3m de rayon et 12m de haut. JdS DEX pour demi-degats. Les morts-vivants et fielons subissent les degats maximaux aux des de radiant. Enflamme les objets non portes.',
    higherLevels: '+1d6 feu et +1d6 radiant par niveau au-dela du 5e.',
    classes: ['Pretre'],
    synergy: 'Apres Dissipation du Mal pour un double assaut contre les morts-vivants.',
    lore: 'Le Pilier de Flamme est la colere de Solarius incarnee. Les Inquisiteurs les plus fervents invoquent ce sort pour purifier les lieux corrompus par la magie de l\'Ombre, laissant derriere eux une terre sanctifiee.'
  },
  {
    id: 'div-019',
    name: 'Guerison de Masse',
    school: 'divine',
    level: 5,
    manaCost: 16,
    castTime: '1 action',
    range: '18m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Une vague de lumiere curative se repand depuis le pretre, touchant tous ses allies blesses dans un rayon genereux. Les blessures se ferment, les os se ressoudent, et la vigueur revient dans les corps epuises.',
    healing: '3d8+WIS a chaque creature choisie',
    effect: 'Soigne jusqu\'a 6 creatures a portee de 3d8 + modificateur de Sagesse PV chacune. Met egalement fin a l\'aveuglement, la surdite et toute maladie sur les creatures soignees.',
    higherLevels: '+1d8 guerison par niveau au-dela du 5e.',
    classes: ['Pretre', 'Gardien'],
    synergy: 'Avec Lueur d\'Espoir, soigne le maximum des des (maximise les d8).',
    lore: 'La Guerison de Masse est le miracle de compassion ultime. Les chroniques racontent que lors de la Bataille de la Riviere Rouge, un unique pretre a soigne cent soldats en une priere, retournant le cours de la bataille.'
  },
  {
    id: 'div-020',
    name: 'Aura Sacree',
    school: 'divine',
    level: 5,
    manaCost: 15,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (un symbole sacre en or)'],
    description: 'Le pretre irradie d\'une lumiere divine si intense que les creatures du mal ne peuvent la supporter. L\'aura confere une protection surnaturelle a tous les allies proches, renforiant leur corps et leur esprit contre la corruption.',
    effect: 'Aura de 9m. Les allies ont un avantage aux JdS. Les creatures celestes, elementaires, fees et fielons dans l\'aura sont desavantages aux jets d\'attaque. Les allies ont resistance aux degats des sorts.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Combine avec Benediction pour des JdS quasi imbattables.',
    lore: 'L\'Aura Sacree est le manteau du champion divin. Seuls les pretres dont la foi est inebranlabie peuvent la maintenir, car toute doute, meme fugace, brise l\'aura comme du verre.'
  },

  // ======================== NIVEAU 6 ========================
  {
    id: 'div-021',
    name: 'Guerison Supreme',
    school: 'divine',
    level: 6,
    manaCost: 22,
    castTime: '1 action',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le pretre canalise une quantite massive d\'energie divine en un seul point de contact, inondant la creature touchee d\'une lumiere curative d\'une intensite aveuglante. Quand la lumiere se dissipe, les blessures les plus graves ont disparu.',
    healing: '70 PV',
    effect: 'Soigne 70 PV et met fin a toute maladie, poison, aveuglement, surdite et malediction sur la cible. Ne peut pas augmenter les PV au-dela du maximum.',
    classes: ['Pretre', 'Gardien'],
    synergy: 'Apres Lueur d\'Espoir, soigne 70 PV au maximum (pas de des a maximiser).',
    lore: 'La Guerison Supreme est le miracle des Grands Pretres, un acte de pure devotion qui consume temporairement la connexion divine du lanceur. Les recipients de ce miracle rapportent avoir vu la lumiere de Solarius lui-meme.'
  },
  {
    id: 'div-022',
    name: 'Festin des Heros',
    school: 'divine',
    level: 6,
    manaCost: 20,
    castTime: '10 minutes',
    range: '9m',
    duration: '24 heures',
    components: ['Verbal', 'Somatique', 'Materiel (nourriture d\'une valeur de 1000 po incrustee de gemmes)'],
    description: 'Le pretre benit un festin somptueux qui se pare d\'une lumiere doree. Chaque bouchee apporte force et vigueur surnaturelles, et les convives quittent la table plus forts, plus resistants et proteges contre le mal.',
    healing: '2d10 PV temporaires',
    effect: 'Jusqu\'a 12 creatures qui consomment le festin gagnent : immunite au poison et a l\'effroi, avantage aux JdS SAG, +2d10 PV temporaires. Dure 24 heures.',
    classes: ['Pretre'],
    synergy: 'Preparation ideale avant une expedition dans une zone de l\'Ombre.',
    lore: 'Le Festin des Heros est un rite ancestral du Temple, remontant a l\'Ere des Sceaux. Les Chevaliers de l\'Aube partagent ce repas sacre avant chaque croisade, et les tables ou il fut servi sont conservees comme reliques.'
  },
  {
    id: 'div-023',
    name: 'Interdiction',
    school: 'divine',
    level: 6,
    manaCost: 24,
    castTime: '10 minutes',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (eau benite, encens rare et poudre de rubis d\'une valeur de 1000 po)'],
    description: 'Le pretre consacre une zone, la protegeant contre les intrusions planaires et les teleportations. L\'espace sanctifie repousse les creatures du mal et empeche tout voyage magique non autorise.',
    effect: 'Zone de 12m x 12m. Empeche les voyages planaires et la teleportation. Les creatures d\'un type choisi (celestes, elementaires, fees, fielons, morts-vivants) subissent 5d10 degats radiants en entrant. Un mot de passe peut etre defini.',
    classes: ['Pretre'],
    synergy: 'Empeche la fuite par teleportation — combine avec Gardien de la Foi.',
    lore: 'Les temples majeurs d\'Aethelgard sont tous proteges par une Interdiction permanente. Le Temple de Solarius a Solaureus possede sept couches d\'Interdiction, rendant toute incursion extraplanaire impossible.'
  },
  {
    id: 'div-024',
    name: 'Mot de Rappel',
    school: 'divine',
    level: 6,
    manaCost: 20,
    castTime: '1 action',
    range: '1,5 km',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le pretre prononce un mot sacre et lui et ses allies sont instantanement transportes dans un lieu sanctifie prealablement designe. Le voyage est accompagne d\'un flash de lumiere doree et d\'un son de cloches lointaines.',
    effect: 'Teleporte le lanceur et jusqu\'a 5 creatures consentantes vers un sanctuaire prealablement designe. Le sanctuaire doit etre un lieu consacre a la divinite du pretre. La teleportation est infaillible.',
    classes: ['Pretre'],
    synergy: 'Evacuation d\'urgence infaillible vers un lieu sur.',
    lore: 'Le Mot de Rappel est le lien indefectible entre le pretre et son sanctuaire. Les pretres itinerants de Solarius designent toujours un temple comme ancrage, et le Mot de Rappel leur permet de fuir les situations les plus desespere.'
  },

  // ======================== NIVEAU 7 ========================
  {
    id: 'div-025',
    name: 'Resurrection Supreme',
    school: 'divine',
    level: 7,
    manaCost: 30,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 25000 po, consomme)'],
    description: 'Le pretre accomplit le plus grand des miracles divins : rappeler une ame depuis l\'au-dela et restaurer completement son corps, meme si celui-ci a ete detruit. Le rituel necessite une foi inebranlabie et un sacrifice materiel considerable.',
    healing: 'PV maximum complets, corps completement restaure',
    effect: 'Ramene a la vie une creature morte depuis moins de 200 ans. Restaure completement le corps, y compris les membres manquants. Neutralise tous les poisons et maledictions. L\'ame doit etre libre et consentante. -4 a tous les jets pendant 4 jours.',
    classes: ['Pretre'],
    synergy: 'Restauration Majeure pour eliminer la penalite post-resurrection.',
    lore: 'La Resurrection Supreme n\'est accordee qu\'aux heros les plus meritants. Le Grand Pretre de Solarius lui-meme doit officier, et le rituel est un evenement majeur qui attire des fideles de tout Aethelgard.'
  },
  {
    id: 'div-026',
    name: 'Symbole Sacre',
    school: 'divine',
    level: 7,
    manaCost: 28,
    castTime: '1 minute',
    range: 'Contact',
    duration: 'Permanent (jusqu\'au declenchement)',
    components: ['Verbal', 'Somatique', 'Materiel (mercure, phosphore, poudre de diamant et d\'opale d\'une valeur de 5000 po)'],
    description: 'Le pretre inscrit un glyphe sacre d\'une puissance devastatrice sur une surface ou dans un objet. Le symbole reste dormant jusqu\'a ce qu\'une condition de declenchement soit remplie, liberant alors sa puissance divine.',
    effect: 'Inscrit un symbole qui se declenche selon une condition. Effets au choix : Mort (10d10 necrotique), Douleur (etourdi pour 1 minute), Terreur (effraye pour 1 minute), Sommeil (inconscient), Etourdissement, Demence. JdS selon l\'effet.',
    classes: ['Pretre'],
    synergy: 'Protege les lieux sacres de maniere permanente. Combine avec Interdiction.',
    lore: 'Les Symboles Sacres protegent les cryptes des Saints d\'Aethelgard. Quiconque profane un tombeau protege par un Symbole fait face a la colere divine eternelle. Certains symboles sont actifs depuis des siecles.'
  },
  {
    id: 'div-027',
    name: 'Temple des Dieux',
    school: 'divine',
    level: 7,
    manaCost: 26,
    castTime: 'rituel 1h',
    range: '36m',
    duration: '24 heures',
    components: ['Verbal', 'Somatique', 'Materiel (un symbole sacre et un reliquaire)'],
    description: 'Un temple ephemere se materialise dans une explosion de lumiere sacree. Les murs sont faits de force divine pure, l\'interieur est chaud et accueillant, et l\'air vibre d\'une energie curative. Ce sanctuaire temporaire offre protection et repos.',
    healing: '2d10 PV par heure de repos',
    effect: 'Cree un temple de 36m x 36m. A l\'interieur : temperature agreable, nourriture et eau pour 100 personnes, 2d10 PV gueris par heure de repos, protection contre le scrutation et les intrusions planaires. Le lanceur controle les entrees.',
    classes: ['Pretre'],
    synergy: 'Combine avec Festin des Heros pour une preparation complete avant la bataille.',
    lore: 'Le Temple des Dieux est le miracle des pretres de campagne, transformant n\'importe quel champ de bataille en sanctuaire. Lors de la Longue Marche vers Coeurfer, un pretre a maintenu ce temple chaque nuit pendant quarante jours.'
  },
  {
    id: 'div-028',
    name: 'Jugement Divin',
    school: 'divine',
    level: 7,
    manaCost: 28,
    castTime: '1 action',
    range: '30m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique'],
    description: 'Le pretre prononce le verdict de sa divinite et un rayon de lumiere pure descend des cieux pour frapper la creature jugee. La lumiere ne brule pas seulement la chair mais aussi l\'ame, et les creatures malfaisantes subissent un tourment indicible.',
    damage: '10d8 radiant',
    effect: 'La cible effectue un JdS CON. Degats complets en cas d\'echec, demi-degats en cas de reussite. Les creatures d\'alignement mauvais subissent +5d8 degats supplementaires. Si les degats reduisent la cible a 0 PV, son ame est detruite (pas de resurrection).',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Suivi de Dissipation du Mal pour purifier la zone.',
    lore: 'Le Jugement Divin est la sentence ultime du Temple de Solarius. Prononce contre les pires criminels et les servants de l\'Ombre, il ne detruit pas seulement le corps mais l\'ame elle-meme, empechant toute forme de retour.'
  },

  // ======================== NIVEAU 8 ========================
  {
    id: 'div-029',
    name: 'Aura Solaire',
    school: 'divine',
    level: 8,
    manaCost: 36,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (un fragment de soleil fossilise)'],
    description: 'Le pretre se transforme en avatar de Solarius, irradiant d\'une lumiere insupportable. Son corps brille comme un soleil miniature, aveuglant les creatures des tenebres et baignant la zone dans une clarte sacree.',
    damage: '6d8 radiant par tour (creatures hostiles dans la zone)',
    effect: 'Lumiere vive dans un rayon de 18m, faible 18m supplementaires. Au debut de chaque tour, creatures hostiles dans la zone lumineuse : JdS CON ou aveuglees et 6d8 degats radiants. Les morts-vivants ont un desavantage. Les allies gagnent 10 PV temporaires par tour.',
    classes: ['Pretre', 'Paladin'],
    synergy: 'Avec Aura Sacree, transforme le pretre en forteresse ambulante de lumiere.',
    lore: 'L\'Aura Solaire est la benediction supremes de Solarius accordee a ses champions. Le Grand Pretre Valorius l\'a maintenue pendant toute la Bataille du Crepuscule, repoussant seul une armee de morts-vivants.'
  },
  {
    id: 'div-030',
    name: 'Controle Celeste',
    school: 'divine',
    level: 8,
    manaCost: 34,
    castTime: '1 action',
    range: '90m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique'],
    description: 'Le pretre invoque la puissance celeste pour manipuler la lumiere elle-meme. Des rayons de soleil concentres peuvent etre diriges comme des armes, guerir les allies, ou creer des zones de lumiere impenetrable aux forces des tenebres.',
    damage: '6d8 radiant par rayon',
    effect: 'Cree un cylindre de lumiere celeste de 18m de rayon. Le lanceur peut creer 4 rayons de 1,5m de large. A chaque tour (action), deplacer les rayons et infliger 6d8 radiant (JdS CON) ou soigner 6d8 PV a un allie touche.',
    classes: ['Pretre'],
    synergy: 'Combine avec Pilier de Flamme pour transformer le champ de bataille en fournaise sacree.',
    lore: 'Le Controle Celeste est l\'art des Pretres Solaires, un ordre secret au sein du Temple de Solarius. Ils pretendent pouvoir entendre la voix du dieu solaire dans chaque rayon de lumiere qu\'ils dirigent.'
  },
  {
    id: 'div-031',
    name: 'Sanctuaire Inviolable',
    school: 'divine',
    level: 8,
    manaCost: 38,
    castTime: '1 action',
    range: '9m',
    duration: '1 heure',
    components: ['Verbal', 'Somatique', 'Materiel (un reliquaire en or contenant une relique sainte)'],
    description: 'Un dome de force divine indestructible se forme autour de la zone designee. A l\'interieur, le temps lui-meme semble ralentir pour favoriser la guerison, et aucune force hostile ne peut penetrer le sanctuaire.',
    healing: '4d10 PV par tour pour les creatures a l\'interieur',
    effect: 'Dome de 9m de rayon. Impenetrable de l\'exterieur (comme Mur de Force mais spherique). Les creatures a l\'interieur guerissent 4d10 PV par tour. Aucune magie hostile ne peut cibler l\'interieur. Le lanceur peut laisser entrer/sortir les creatures.',
    classes: ['Pretre'],
    synergy: 'Refuge ultime pendant Aura Solaire ou apres un combat difficile.',
    lore: 'Le Sanctuaire Inviolable est le miracle de dernier recours, utilise quand tout semble perdu. Les legendes racontent que lors du cataclysme de l\'Ere des Sceaux, un Sanctuaire Inviolable a protege une cite entiere de l\'annihilation.'
  },
  {
    id: 'div-032',
    name: 'Parole Divine',
    school: 'divine',
    level: 8,
    manaCost: 35,
    castTime: '1 action',
    range: '9m',
    duration: 'Instantane',
    components: ['Verbal'],
    description: 'Le pretre prononce un mot du langage divin, un son qui n\'appartient pas au monde mortel. La vibration sacree frappe les creatures selon leur puissance : les plus faibles sont detruites, les autres debilitees de diverses manieres.',
    effect: 'Toutes les creatures hostiles a portee sont affectees selon leurs PV actuels : 50 PV ou moins — tuees instantanement ; 51-80 PV — aveuglees et assourdies 1h ; 81-100 PV — assourdies 1 minute ; 101+ — aucun effet. Les extraplanaires sont bannies.',
    classes: ['Pretre'],
    synergy: 'Apres avoir affaibli les ennemis avec d\'autres sorts pour les amener sous le seuil de PV.',
    lore: 'La Parole Divine est un fragment du Verbe Createur, le son qui aurait faconne Aethelgard. Prononcer ce mot est un acte de foi absolue, car la moindre imperfection dans la prononciation peut se retourner contre le lanceur.'
  },

  // ======================== NIVEAU 9 ========================
  {
    id: 'div-033',
    name: 'Resurrection Veritable',
    school: 'divine',
    level: 9,
    manaCost: 45,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un diamant d\'une valeur de 50000 po, consomme)'],
    description: 'Le plus grand miracle de guerison connu des mortels. Le pretre transcende les barrieres entre la vie et la mort, reconstituant un corps a partir de rien et y invitant l\'ame. Meme les morts depuis des siecles peuvent etre rappeles.',
    healing: 'PV maximum complets, corps parfaitement restaure',
    effect: 'Ramene a la vie une creature morte depuis n\'importe quelle duree. Restaure le corps meme s\'il a ete completement detruit (un fragment suffit ou le nom complet). Aucune penalite post-resurrection. L\'ame doit etre libre et consentante.',
    classes: ['Pretre'],
    synergy: 'Sort ultime de resurrection — annule meme la destruction d\'ame du Jugement Divin si lance dans l\'heure.',
    lore: 'La Resurrection Veritable est le miracle des miracles, un acte qui defie l\'ordre naturel avec la benediction directe de Solarius. On dit que chaque Resurrection Veritable cree une nouvelle etoile dans le ciel d\'Aethelgard.'
  },
  {
    id: 'div-034',
    name: 'Intervention Divine',
    school: 'divine',
    level: 9,
    manaCost: 50,
    castTime: '1 action',
    range: 'Ligne de vue',
    duration: 'Variable',
    components: ['Verbal', 'Somatique'],
    description: 'Le pretre lance un appel desespere a sa divinite, et Solarius repond directement. L\'intervention divine se manifeste de maniere spectaculaire — le ciel s\'ouvre, une lumiere aveuglante descend, et la volonte du dieu se fait sentir.',
    effect: 'Le MJ determine l\'intervention en fonction de la situation. Exemples : reproduction de tout sort divin, annulation d\'un evenement, teleportation d\'une armee, guerison de masse, destruction d\'un artefact mauvais. Utilisable une seule fois par mois.',
    classes: ['Pretre'],
    synergy: 'Sort universel divin — l\'intervention peut prendre toute forme.',
    lore: 'L\'Intervention Divine n\'est pas un sort a proprement parler — c\'est une supplication directe a Solarius. Le dieu repond selon son propre jugement, et son aide n\'est jamais exactement celle attendue. Mais elle est toujours celle qui est necessaire.'
  },
  {
    id: 'div-035',
    name: 'Bastion de Lumiere',
    school: 'divine',
    level: 9,
    manaCost: 44,
    castTime: '1 action',
    range: '30m',
    duration: 'Concentration, 10 minutes',
    components: ['Verbal', 'Somatique', 'Materiel (un calice en mithral rempli d\'eau benite)'],
    description: 'Une forteresse de lumiere pure se dresse autour de la zone designee, ses murs de radiance impenetrable repoussant les tenebres. A l\'interieur, les allies sont gueris, proteges et fortifies par la grace divine.',
    healing: '6d8 PV par tour',
    effect: 'Forteresse de lumiere de 18m de rayon. Les allies : +4 CA, resistance a tous les degats, 6d8 guerison par tour. Les ennemis ne peuvent pas entrer (JdS CHA DD 22). Les morts-vivants dans un rayon de 30m subissent 8d8 radiant par tour.',
    classes: ['Pretre'],
    synergy: 'Ultime defense divine — combine avec Aura Solaire pour une destruction radiante totale.',
    lore: 'Le Bastion de Lumiere n\'a ete invoque que lors des heures les plus sombres d\'Aethelgard. La derniere fois fut lors de la Chute du Dernier Sceau, quand le Grand Pretre Aelindra dressa un bastion qui tint pendant sept jours contre les armees de l\'Ombre.'
  },
  {
    id: 'div-036',
    name: 'Apocalypse Sacree',
    school: 'divine',
    level: 9,
    manaCost: 48,
    castTime: '1 action',
    range: '300m',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (la relique personnelle d\'un Saint)'],
    description: 'La colere divine se dechaine sur les ennemis de la foi. Des cometes de lumiere sacree pleuvent du ciel, le sol tremble, et un choeur angelique tonitruant annonce le jugement final sur le champ de bataille.',
    damage: '12d10 radiant + 8d10 force',
    effect: 'Zone de 24m de rayon. JdS CON DD 22 pour demi-degats. Les morts-vivants et fielons subissent des degats maximaux. Les creatures tuees ne peuvent pas etre relevees comme morts-vivants. Sanctifie la zone pendant 1 an.',
    classes: ['Pretre'],
    synergy: 'Apres Bastion de Lumiere pour proteger les allies de l\'explosion.',
    lore: 'L\'Apocalypse Sacree est le jugement final de Solarius sur les forces des tenebres. On dit que son utilisation laisse une marque permanente sur le monde — les champs ou elle fut invoquee ne connaissent plus jamais la nuit.'
  },

  // ======================== NIVEAU 10 ========================
  {
    id: 'div-037',
    name: 'Avatar de Solarius',
    school: 'divine',
    level: 10,
    manaCost: 60,
    castTime: '1 action',
    range: 'Personnel',
    duration: 'Concentration, 1 minute',
    components: ['Verbal', 'Somatique', 'Materiel (la Couronne Solaire, artefact unique)'],
    description: 'Le pretre devient le vaisseau de Solarius lui-meme. Son corps se transforme en un etre de lumiere pure de 6m de haut, irradiant une chaleur et une majeste divines. Pendant un bref instant, le dieu marche a nouveau parmi les mortels.',
    damage: '15d10 radiant (attaque au corps a corps)',
    healing: '50 PV par tour a tous les allies dans 30m',
    effect: 'Transformation en avatar divin. Stats remplacees : FOR 30, CON 30, CA 25. Immunite a tous les degats non divins. Attaque au CaC : 15d10 radiant. Tous les allies dans 30m guerissent 50 PV par tour. Morts-vivants detruits dans 18m. Apres : 7 niveaux d\'epuisement.',
    classes: ['Pretre'],
    synergy: 'Sort ultime divin — aucune synergie necessaire.',
    lore: 'L\'Avatar de Solarius est le miracle des legendes, jamais vu depuis l\'Ere des Sceaux. Le prix est immense — le pretre frole la mort apres la transformation. Mais pendant une minute, la lumiere divine eclaire Aethelgard comme au Premier Jour.'
  },
  {
    id: 'div-038',
    name: 'Redemption Ultime',
    school: 'divine',
    level: 10,
    manaCost: 55,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (un coeur de diamant pur d\'une valeur de 100000 po, consomme)'],
    description: 'Le pretre accomplit un miracle de compassion absolue — purifier une creature corrompue de tout mal, restaurer son ame a son etat originel et lui offrir une seconde chance. Meme les creatures les plus sombres peuvent etre rachetees.',
    effect: 'Purge une creature de toute corruption, malediction, possession ou influence malefique de maniere permanente. Change l\'alignement en neutre ou bon. Restaure les souvenirs effaces par la corruption. Peut meme racheter un mort-vivant intelligent, le ramenant a la vie.',
    classes: ['Pretre'],
    synergy: 'Peut annuler les effets de la corruption de la magie de l\'Ombre.',
    lore: 'La Redemption Ultime est l\'expression la plus pure de la misericorde divine. Le Grand Pretre Thalion aurait rachete le liche Malachar, le ramenant a la vie mortelle et a la sante d\'esprit. Cet acte reste le plus debattu de l\'histoire theologique d\'Aethelgard.'
  },
  {
    id: 'div-039',
    name: 'Eternite Benie',
    school: 'divine',
    level: 10,
    manaCost: 65,
    castTime: 'rituel 1h',
    range: 'Contact',
    duration: 'Permanent',
    components: ['Verbal', 'Somatique', 'Materiel (un phylactere solaire forge dans la lumiere de l\'aube, artefact unique)'],
    description: 'Le pretre accorde la benediction ultime de Solarius : la vie eternelle dans la grace divine. La creature touchee transcende la mortalite, son corps ne vieillit plus et sa vitalite est maintenue par un flux constant d\'energie divine.',
    effect: 'La cible cesse de vieillir et ne peut mourir de causes naturelles. Immunite aux maladies et aux poisons. Regeneration de 10 PV par tour. Si tuee, revient a la vie apres 24h au sanctuaire le plus proche de Solarius. Peut etre annule par Souhait ou volonte divine.',
    classes: ['Pretre'],
    synergy: 'La protection ultime pour un champion d\'Aethelgard.',
    lore: 'L\'Eternite Benie n\'a ete accordee qu\'aux plus grands heros d\'Aethelgard. On raconte que les cinq Gardiens des Sceaux originaux ont recu cette benediction, et que certains veillent encore dans l\'ombre, attendant le jour ou les Sceaux auront besoin d\'eux.'
  },
  {
    id: 'div-040',
    name: 'Lumiere du Premier Jour',
    school: 'divine',
    level: 10,
    manaCost: 70,
    castTime: '1 action',
    range: '1,5 km',
    duration: 'Instantane',
    components: ['Verbal', 'Somatique', 'Materiel (un fragment du Soleil Primordial, artefact legendaire)'],
    description: 'Le pretre invoque la lumiere qui a eclaire le premier jour d\'Aethelgard, avant que les tenebres n\'existent. Cette lumiere primordiale annihile toute forme d\'ombre, de corruption et de mal, purifiant tout ce qu\'elle touche.',
    damage: '30d10 radiant (contre toute creature malefique)',
    effect: 'Sphere de lumiere de 300m de rayon. Toute creature malefique : 30d10 radiant (pas de JdS). Toute corruption, malediction, enchantement sombre est dissipe. Les morts-vivants sont detruits definitivement. Les allies sont gueris a leur maximum de PV. Zone sanctifiee pendant 1 siecle.',
    classes: ['Pretre'],
    synergy: 'Purifie toute zone corrompue par la magie de l\'Ombre ou les Sceaux brises.',
    lore: 'La Lumiere du Premier Jour est le miracle le plus puissant que puisse invoquer un mortel. On dit que c\'est la lumiere que Solarius a utilisee pour forger le monde, et que l\'invoquer est un acte de re-creation. Nul ne l\'a lancee depuis la fin de l\'Ere des Sceaux.'
  }
];
